### ISSUE TITLE
ProxyJump support

### ISSUE THREAD

**Issue by 1-61803** [paramiko/paramiko#1018]
`OpenSSH` supports `-J` or `ProxyJump` since version `7.3`. Is it  possible to support this feature to use multiple jump hosts? For example:

`ssh -q -J user1@jumphost1,user2@jumphost2,user3@jumphost3 user@server`

**Comment by bitprophet** [comment]
Thanks for the request!

Fabric 2 (in beta) supports this via nested gateway arguments, using Paramiko's ability to take socket-like objects: http://docs.fabfile.org/en/v2/concepts/networking.html#proxyjump

Paramiko itself doesn't tend to implement high level features like this on its own since it's not clear where exactly users would expect it to kick in, it's more building-block style. And as you can see above, client code can easily leverage existing Paramiko functionality to get the desired behavior.

**Comment by danihodovic** [comment]
Is it possible to get ProxyJump working without having to use Fabric?

**Comment by ploxiln** [comment]
Here's a minimized/reduced example of how fabric does a single level of proxy-jump:

```python
def connect(host, user, password, gateway=None):
    client = paramiko.SSHClient()
    sock = None
    if gateway:
        gw_client = connect(host, user, password)
        sock = gw_client.get_transport().open_channel(
            'direct-tcpip', (host, 22), ('', 0)
        )
    )
    kwargs = dict(
        hostname=host,
        port=22,
        username=user,
        password=password,
        sock=sock,
    )
    client.connect(**kwargs)
    return client
```

**Comment by danihodovic** [comment]
Thanks @ploxiln !

**Comment by sweenu** [comment]
It is very confusing when you first start with paramiko thinking it is going to behave the same way SSH does everywhere on your machine.
It was hard to debug because I really did not expect part of my config to be ignored. Especially considering that `ProxyJump`s are just `ProxyCommand`s really.
I think you should reconsider having support for `ProxyJump`s. I'd gladly look into submitting a PR.

**Comment by lilachassor** [comment]
Hi,
can you show the example for proxy jump but with more than one proxy jumps?
