### ISSUE TITLE
Python paramiko send 'CTRL-ALT-6-x' to exit console port

### ISSUE THREAD

**Issue by Jr0ussy** [paramiko/paramiko#1052]
I'm using paramiko to ssh into an access server and connect to a console port. Everything is working fine except when it's time to exit the console port, I must do a 'CTRL-ALT-6 follow by x'. 

I tried:
x.send("\036\px")

But it doesn't seem to work. How can I exit the console port correctly?

**Comment by bitprophet** [comment]
Unfortunately I don't believe there's anything else you can do on the Paramiko end besides using `send` (for example, `send(<interrupt bytes>` works fine on POSIX systems for submitting keyboard interrupts.) So this likely comes down to the details of what bytes you put into `send`, and/or how many times you call `send`.

I'm not familiar with the server in question but for example, it may be tuned for human use, and may simply be expecting more time to pass (or for its terminal prompt state to change, or whatever) between the `CTRL-ALT-6` and the `x`. But since you're using a single `send` those bytes all get submitted immediately. So e.g. one thing to try, if my wild guess turns out to be accurate, might be two `send` calls with a `time.sleep()` in between.

Going to close as "no action can be taken" but leaving discussion open.

**Comment by Jr0ussy** [comment]
I tried this, it didn't worked : 

    x.send("\036\p")
    time.sleep(1)
    x.send("x")
    time.sleep(1)

Can someone confirm that \036\p is CTRL-ALT-6 ?
