### ISSUE TITLE
Difficulty escaping quotemarks for commands over SSH with paramiko -> /usr/sbin/ss dport :22 and sport :22

### ISSUE THREAD

**Issue by gronka** [paramiko/paramiko#1090]
I have a command that I've been able to run locally with subprocess.run() to read ports in use for SSH:
`/usr/sbin/ss -tpi -o state established '( dport = :22 or sport = :22 )'`

I can run this command from a terminal with minor modification:
`ssh $hostname "sudo /bin/bash -c \"/usr/sbin/ss -tpi -o state established '( dport = :22 or sport = :22 )'\"" `

I cannot for the life of me figure out how to run this command through paramiko. The sudo /bin/bash -c portion is necessary due to security restrictions (which I might be able to get altered).

I know the issue is related to escaping quotemarks (and sometimes parentheses) in python vs in a shell. I've tried methods such as replacing all quotes with `'\''`. I think a barrier is that python can interpret string-escapes differently than a shell, so python is removing some of my formatting before sending the command over SSH.

Any leads would be greatly appreciated.

**Comment by bitprophet** [comment]
I don't actually see anything wrong with your setup there, taking your exact snippet and plunking the `"sudo /bin/bash -c \"...\""` string into eg `Client.exec_command()` ought to work correctly:

- Python doesn't care about parentheses at all within strings (only quotes, backslashes, curly braces for format placeholders, etc.)
- You're already backslash-escaping the inner double-quotes, so that should be fine.
- Single-quotes within a double-quoted string (or vice versa) do not need any escaping.

If you can provide actual error output that might help us figure out what's breaking for you.

Gonna close this as "likely no action to be taken" but do report back, hopefully I or another can spot something in your output and point you to the right solution :)

**Comment by gronka** [comment]
Thanks for the open-offer!

To my utter dismay, I logged into our server today, and the command is running perfectly! A deployment went out this morning - no changes were made that would directly effect this, but perhaps something was misconfigured... I hate mysteries like this, haha.

Anyways, for posterity, here is the error message:
```
(Pdb) stderr.readlines()
['Bitbucket cannot not execute "sudo /bin/bash -c "/usr/sbin/ss -tpi -o state established \'( dport                                                    = :22 or sport = :22 )\'"". The command is not supported as entered.\n', '\n', 'Ensure you are using                                                    a supported SCM, check the syntax and try again.\n']
```

When I was toying with other ways to run the command on bash, this was the most common error:
`bash: syntax error near unexpected token `('`

**Comment by bcjarrett** [comment]
No need to reopen the ticket, but this was the only relevant hit on google, so this is here in case it helps anyone else. 

When connecting to a windows server with paramiko double quotes are unexpectedly removed:
```python
ssh = paramiko.SSHClient()

# These don't work, all double quotes are stripped
ssh.exec_command("powershell MyCommand -Param \"new user\")
ssh.exec_command('powershell MyCommand -Param "new user"')

# This works by sending single quotes instead
ssh.exec_command("powershell MyCommand -Param 'new user'")
```
