### ISSUE TITLE
SSHClient.exec_command() timeout problems

### ISSUE THREAD

**Issue by DanLipsitt** [paramiko/paramiko#1117]
The below script times out as expected if the `timeout` is set to `1` but runs indefinitely if it's `2`. It's a simple script, so feel like I must be misunderstanding something. What's going on?

```python
import socket
import sys
from getpass import getpass

from paramiko.client import SSHClient, AutoAddPolicy

COMMAND = 'ping localhost'


def ssh_timeout(host, user, password, timeout):
    client = SSHClient()
    client.load_system_host_keys()
    client.set_missing_host_key_policy(AutoAddPolicy)

    client.connect(host, username=user, password=password)

    try:
        (stdin, stdout, stderr) = client.exec_command(
            COMMAND, timeout=timeout)
        for line in stdout:
            print line
    except socket.timeout:
        print 'Timed out!'
    else:
        print 'Command completed.'


if __name__ == '__main__':
    host, user, timeout = sys.argv[1:]
    timeout = float(timeout)
    password = getpass('Password for {}@{}: '.format(user, host))
    ssh_timeout(host, user, password, timeout)
```

**Comment by radssh** [comment]
`ping localhost` will (normally) run forever, delaying 1 second in between each ping attempt. When the Paramiko timeout is set to 1, the 2nd attempt has a small propagation delay (plus the 1 second interval), so the `for line in stdout:` loop raises a `socket.timeout` exception when the next line of output cannot be read prior to the timeout. When you set the timeout value to 2 (or higher), each line of output can be successfully read within 2 seconds, and the loop can continue as long as the `ping` command yields lines of output.

Try limiting the ping count by setting `COMMAND = 'ping localhost -c 5'` so that the ping can naturally run to completion.

**Comment by DanLipsitt** [comment]
@radssh Thanks for the detailed explanation, that makes sense. The `ping` command itself isn't important here, it's just a way to demonstrate the behavior that was puzzling me. I've submitted PR #1118 to clarify the timeout documentation. Comments welcome.
