### ISSUE TITLE
2.6 support dropped in a minor release

### ISSUE THREAD

**Issue by dmtucker** [paramiko/paramiko#1119]
This is a backward-incompatible change ☹️ 

It (#1070) says targeted for 3.0, but it looks like it was shipped in 2.4.0.
Was that a mistake?

Either way, I would request support be restored in 2.4.1 and dropped again in 3.0 to properly adhere to semantic versioning (assuming that is the versioning scheme used by this project).

**Comment by bitprophet** [comment]
Literally can't win - some folks complain when you go too slow, others when you go too fast :sob:

Point is really just that, as of this point in time, Python 2.6 is no longer supported. Please pin your dependencies to `<2.4` if that's a problem - thanks!

**Comment by bitprophet** [comment]
To clarify, since this is an issue dear to my heart & causes me a lot of grief:

- If we _had_ called Paramiko 2.4, Paramiko 3.0 instead, there would not have been any Paramiko 2.5, 2.6 etc. Only 3.0, 3.1, 3.2. That's what I mean by "as of this point in time."
- Python interpreter version is a fraught part of Python-lib semantic versioning; for users on Python 2.7+ or 3.4+, calling this Paramiko 3.0 would have been needlessly confusing as there's no API change or anticipated instability.
- Put another way, it's only a breaking change for you and the other <3% of users still on Python 2.6. I'm not happy about leaving _anybody_ out in the cold, but given the need to balance developer sanity with user support, the latter starts to lose out at such low numbers :(
- For more details and handwringing, see the rest of #1070 (which, yes, I never did update the milestone on - just removed it now that it's merged.) You can see I went back and forth on this a lot; it was not a flippant decision!

**Comment by dmtucker** [comment]
We will pin to `<2.4` since that's really the only workaround I can see... At the end of the day, we suck for still needing 2.6, and I'm all for leaving it in the dust. In fact, people should be thinking about dropping 2.7 in the not too distant future. We just aren't there yet.

> The only real difference is the number that 2.6 users have to pin at. It's now <2.4 instead of <3.0.

FWIW, I typically use [the compatible release operator from PEP440](https://www.python.org/dev/peps/pep-0440/#compatible-release) (e.g. `~=2.0`).

> Python interpreter version is a fraught part of Python-lib semantic versioning; for users on Python 2.7+ or 3.4+, calling this Paramiko 3.0 would have been needlessly confusing as there's no API change or anticipated instability for them. Makes it less clear-cut than a library dependency change or an actual API change.

I'm not sure the distinction matters. Bumping the major version lets dependents know that they should take a look at what's changed before moving to the next version because *something* will break and they should take action if they will be affected. When they realize they don't care because they don't need 2.6, bumping the dep to the new major version is trivial. The exact same thing would happen if, for example, a deprecated API were removed instead.

> Put another way, it's only a breaking change for you and the other <3% of users still on Python 2.6. I'm not happy about leaving anybody out in the cold, but given the need to balance developer sanity with user support, the latter starts to lose out at such low numbers :(

I would guess that many (most?) backward-incompatible changes don't affect all or even a majority of dependents. Still, a backward-incompatible change is a backward-incompatible change. Making one may not be ideal, but that's the nature of software development. Standards are only useful if they are followed...

> You can see I went back and forth on this a lot; it was not a flippant decision!

I believe you, and I don't mean to downplay/discredit that. Thanks for your work! Paramiko is awesome 😎
