### ISSUE TITLE
Running on Windows unknown hosts

### ISSUE THREAD

**Issue by urezdaye** [paramiko/paramiko#1279]
Hello all:
I am constantly running into an issue where I cannot log onto hosts using paramiko on Windows.
It continually rejects connections despite including the missing host key policy to AutoAddPolicy.
See section:
```    client = paramiko.SSHClient()
          client.load_system_host_keys()
          client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
          keyfile = os.path.join(expanduser("~"), "Desktop/key.pem")
          k = paramiko.RSAKey.from_private_key_file(keyfile)
          client.get_host_keys().add(server, 'ssh-rsa', k)
```

Does Paramiko support use in Windows environments?

**Comment by bitprophet** [comment]
I'd make sure you turn on logging (a basic `import logging; logging.basicConfig(level=logging.DEBUG)` should suffice) to see if anything useful comes out of that, it's possible something is just broken with your attempt to load the keyfile for example.

Otherwise, please post some more details about your error message (& that debug log output).

We absolutely have many Windows users so this should not be a high level platform support issue, I can say that much :)

Closing as probably not actionable but not locking.
