### ISSUE TITLE
How to connect with both public key and google authenticator (auth_interactive) ?

### ISSUE THREAD

**Issue by Vincent-Shi** [paramiko/paramiko#1289]
Hi,
    I want to connect my server with both public key and google authenticator, i use paramiko.Transport() to solve this situation. Here are my code:
```
def inter_handler(title, instructions, prompt_list):
    resp = []  #Initialize the response container
    for pr in prompt_list:
        if pr[0].startswith('Verification'):
            resp.append(<auth code>)
    return tuple(resp)

import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((<hostname>, 22))
ts = paramiko.Transport(sock)
ts.start_client(timeout=10)
rsa_key = paramiko.RSAKey.from_private_key_file(<my_private_key_path>)
ts.add_server_key(rsa_key)
ts.auth_interactive(username=<username>, handler=inter_handler)

ts.is_authenticated() // returned False
```
After running this, i called ts.is_authenticated(), but it returned False. 
Can anyone help me? Thanks a lot.

**Comment by bitprophet** [comment]
I don't have time to deep dive on this but I _think_ you are going in the right direction here, not sure why it didn't work. I know users have successfully used TOTP for things like Duo Security's implementation without issue, at least since some bugs were fixed a couple years back (maybe make 100% sure you're on a recent version?).

Closing as probably not actionable (there may be some minor tweaks you have to make on your end, like using a different `auth_` method?) but not locking, hopefully someone else will have time to dig.

**Comment by chrisinmtown** [comment]
The sample code shows no use of the `Transport` class's `auth_publickey` method, I sorta think that is required? If I read the code correctly, the `auth_server_key` method is only appropriate for server (not client) mode.
