### ISSUE TITLE
Match Confusing Paramiko SSH Config Parsing?

### ISSUE THREAD

**Issue by geoffreywiseman** [paramiko/paramiko#1297]
I was attempting to use `sshtunnel`, which has `paramiko` as a dependency, and hit an issue where the SSH configuration file parsing was picking up the wrong username. I can work around it, but it *seems* like a Paramiko defect to me.

Here's the related issue on `sshtunnel`:
https://github.com/pahaz/sshtunnel/issues/133

Essentially, given this configuration file:
```
Match Host 10.0.*.* User ec2-user
  User ec2-user
  IdentityFile ~/path/to/keys/key.pem
Host *
  UseKeychain yes
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_rsa
VisualHostKey yes
```

Paramiko seems to decide that for host `dev`, the username should be `ec2-user`, which it shouldn't be:

```
Python 3.6.5 (default, Jun 24 2018, 13:09:28)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from paramiko.config import SSHConfig
>>> config = SSHConfig()
>>> cfg_file='./ssh-cfg-simple'
>>> with open(cfg_file) as f:
...     config.parse(f)
...
>>> config.lookup('dev')
{'match': 'Host 10.0.*.* User ec2-user', 'user': 'ec2-user', 'identityfile': ['/path/to/key.pem', '/path/to/ssh/key'], 'usekeychain': 'yes', 'addkeystoagent': 'yes', 'visualhostkey': 'yes', 'hostname': 'dev'}
>>>
```

I cannot swear with certainty that there's nothing wrong with my configuration file (since I haven't found a canonical ssh configuration linter/parser), but I can assert that it works fine for me with ssh, just not with Paramiko.

**Comment by sbz** [comment]
I'm trying to have a look to this issue with the OpenSSH `Match` directive in the client `~/.ssh/config`

Reading about the [Match](https://man.openbsd.org/ssh_config#Match) directive and the existing OpenSSH Portable tests cases for covering the [config](https://github.com/openssh/openssh-portable/blob/master/regress/cfgmatch.sh). It turns out, there is not test case for `Match Host` in the same time (have a look to `trace message`)

I added a test case `test_SSHConfig_match_supported_SSHConfigDict_instances` in the commit 507d128 to cover this issue on my branch [sbz/paramiko/issue-1297](https://github.com/sbz/paramiko/tree/issue-1297)

I'm investigating and trying to figure out if we can solve it.

**Comment by bitprophet** [comment]
Believe this duplicates #717, let's roll into that.

**Comment by geoffreywiseman** [comment]
Yes, I agree, it does sound like #717 is the superset of this problem.
