### ISSUE TITLE
Support new key format

### ISSUE THREAD

**Issue by dj-foxxy** [paramiko/paramiko#1313]
I generated a key using `ssh-keygen` but it's now in a different format and paramiko failed saying `Authentication failed.`. I had to make a new key like this `ssh-keygen -m PEM`.

**Comment by elijahbal** [comment]
Yes, it is because openssh has its own format for generating keys, that is not understood but almost all the implementations out there.

This is a low priority issue but still a problem for most users. I am not aware of a python implementation of that openSSH internal format, but there is definitely a need for having interoperability improved in this domain.

**Comment by PierreSelim** [comment]
This change from OpenSSH is unfortunate ;(

**Comment by radssh** [comment]
Until the file format is natively supported by Paramiko, you can still use these keys by making them accessible via `ssh-agent`. That way, it is the OpenSSH utility that loads and reads the file format, then makes the key available so that Paramiko is able to perform the signing of data by proxy, instead of having to read and interpret the private key contents.

**Comment by PierreSelim** [comment]
Thanks for this. To be clear, I find unfortunate that OpenSSH change formats of things such as SSH key not really the fact paramiko does not support it yet.

**Comment by hyperknot** [comment]
This is a problem with recent macOS, whose OpenSSL ssh-keygen has changed the default format. Now a generated SSH key starts with:
```
-----BEGIN OPENSSH PRIVATE KEY-----
```

instead of the supported
```
-----BEGIN RSA PRIVATE KEY-----
```

To generate a supported key, use the following command:
```
ssh-keygen -t rsa -b 4096 -C "email@email.com" -m PEM
```

**Comment by SharkFourSix** [comment]
@hyperknot This does not work for me. What the hell. Any other solution?

**Comment by hyperknot** [comment]
@SharkFourSix remove the old keys and make a new one. It should start with RSA PRIVATE KEY.

**Comment by SharkFourSix** [comment]
hyperknot I inadvertently updated paramiko and it seems it's fixed.

**Comment by bitprophet** [comment]
This seems like it may concern the new OpenSSH key format - see #1343.

**Comment by Neil-Jubinville** [comment]
Crazy troubleshooting to arrive here :)   -m PEM is the answer that worked for me.
