### ISSUE TITLE
Receiving ^[[6n during recv with invoke_shell, then recv_ready() is False for 5 minutes

### ISSUE THREAD

**Issue by Vuader** [paramiko/paramiko#1350]
When using invoke_shell(), even before sending on the channel, I expect to be able to recv(65535) at least up to the end of the login banner and prompt. Using Paramiko on Zyxel OLT2406.

At least, I am able to observe this behaviour on older firmware. However, on newer firmware (V4.02(AAVA.4)C0) I receive the copyright notice, but before the hostname arrives in the receive buffer, "^[[6n" appears, and and then no more characters. At this point recv_ready() is False. After waiting EXACTLY 300 seconds, recv_ready() becomes True, and the remainder of the login prompt (the hostname) can be read.

When manually SSH'ing to the device, (ie not using paramiko, just native ssh client) all is fine, and there is no delay before seeing the hostname in the prompt.

**Comment by radssh** [comment]
Looks like the Zyxel host is expecting a fully-functioning terminal on the client end... Hunting the ANSI escape code sequences, there seems to be one matching ^[[6n (where ^[ represents <ESC>)
```
Report Cursor Position | {ESC}[6nReturns the current row and column position of the cursor in the form {ESC}[<row>;<col>R
-- | --
```
I'll posit that the server is waiting on the client side to reply to that request, and waits 500 seconds for a reply, before resuming with streaming the rest of the output.  Are you calling `request_pty()` before `invoke_shell()`? That should inform the server side that the terminal type (default) is `vt-100` which should avoid the sending/receiving of extended ANSI sequences.

You might also want to compare the verbose output of the native SSH client (`ssh -vv`) to see what pty terminal type it is setting up for your working reference session.

**Comment by Vuader** [comment]
Thanks for the advise @radssh , sounds like a good posit.

However, I'm missing something - I can't seem to find any reference to a `request_pty()` method. I can only see `get_pty()`, but this is a method of the Channel Class, for which the object is created with `invoke_shell()`, so can thus only be called thereafter.

When running:

```
client_pre = paramiko.SSHClient()
client_pre.load_system_host_keys()
client_pre.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client_pre.connect(o, 22, OLTs[o]['username'], OLTs[o]['password'])
time.sleep(1)
conn =client_pre.invoke_shell()
conn.get_pty()
```

Then this:
```
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 63, in _check
    return func(self, *args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 187, in get_pty
    self._wait_for_event()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 1198, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.
```

Also, I'm not able to determine from `ssh -vvv` the PTY terminal type:

```
$ egrep -i 'pty|vt' /tmp/sshstderr 
debug2: channel 0: request pty-req confirm 1
debug2: PTY allocation request accepted on channel 0
```

**Comment by radssh** [comment]
Indeed - looking at the **SSHClient** method for `invoke_shell()`, it prefixes the **Channel** `invoke_shell()` call with an explicit `get_pty()` defaulting to vt100. You can pass in the reqeusted term type in the parameters to `invoke_shell(term='blah')` to try a different terminal type, perhaps even a nonsensical one, to try to trick the server into not sending codes in the output stream that expect a response.
It turns out that the sequence is not extended ANSI at all, but part of the core VT100 codes (See https://www.csie.ntu.edu.tw/~r92094/c++/VT100.html), but it is a bit odd that the server would be using such codes unless it was driving a full-screen session as opposed to a more basic streamed output.

Another thing you could try (short of doing a comprehensive VT100 terminal emulation) is to guess that if `recv_ready()` is failing, to blindly send the VT100 response code reporting the cursor location, with some sensible made up values ('\x1b1;1R'), to attempt to unblock the server's 5 minute wait. That could do the trick.

**Comment by Vuader** [comment]
@radssh you are a legend!

the `term='blah'` had no effect, but the cursor location did the trick

thanks, I really appreciate your assistance.

**Comment by marv2018** [comment]
> ('\x1b1;1R')

This should be ('\x1b[1;1R') not ('\x1b1;1R')
