### ISSUE TITLE
Base64 incorrect padding

### ISSUE THREAD

**Issue by 108806** [paramiko/paramiko#1361]
```
import base64
import paramiko
key = paramiko.RSAKey(data=base64.b64decode(b'AAA...'))
client = paramiko.SSHClient()
client.get_host_keys().add('ssh.example.com', 'ssh-rsa', key)
client.connect('ssh.example.com', username='strongbad', password='thecheat')
stdin, stdout, stderr = client.exec_command('ls')
for line in stdout:
    print('... ' + line.strip('\n'))
client.close()
```

> File "C:\Users\phantom\AppData\Local\Programs\Python\Python37-32\Lib\base64.py", line 87, in b64decode
>   return binascii.a2b_base64(s)
> 
> binascii.Error: Incorrect padding

Totally dont know how to deal with this.

**Comment by ploxiln** [comment]
This problem is not related to paramiko, it's just this part: `base64.b64decode(b'AAA...')`

It means that the binary string you're passing to `b64decode()` does not end with the expected number of `=` chars, which are the padding, which are related to using base64 to represent a number of bytes which is not divisible by 3. (What you're passing to `b64decode()` might not just have wrong padding, but might actually be truncated, or include extra junk at the end.)

**Comment by liuyangc3** [comment]
facing same issue when parse ca based files, raised a fix here https://github.com/paramiko/paramiko/pull/2291

**Comment by bskinn** [comment]
Given the age of the ticket and the eval as being not a paramiko problem, I'm going to close.

@108806, if you're still having problems related to this, please open a new ticket. Thanks!
