### ISSUE TITLE
Banner not returning (but it is there)

### ISSUE THREAD

**Issue by micahg** [paramiko/paramiko#1375]
Hi,

I'm using paramiko 2.4.2, python 3.7.2, windows 10.

After connecting to a host, I'm expecting the banner to return. I can see in the paramiko log that it does return:

`INF [20190201-15:50:37.098] thr=1   paramiko.transport: Auth banner: b'REDACTED'`

(**note**, I redacted the banner, it actually comes back with the banner I see when I ssh in manually). Anyhow, when I issue

`banner = client._transport.get_banner()`

the banner variable is None.

Strangley, this *was* working and seems to have just stopped. Any advice would be greatly appreciated. 

Thanks,

**Comment by radssh** [comment]
Seems related to #432 which is yet to be merged. Essentially, the server sends the banner to the client *after* authentication has started, so the code stashes the banner content into the `AuthHandler` object, where the `Transport` can fetch it via `get_banner()`. Unfortunately, since the `Transport` may create subsequent `AuthHandler` objects if multiple authentication attempts are made, the banner content stashed in the first `AuthHandler` winds up being thrown away, since the server only sends that protocol message one time.
It probably worked for you previously without issue if you were successfully authenticating on your first attempt, and changed because the authentication is now needing an additional attempt.

**Comment by micahg** [comment]
Hi,

I read #432 and applied https://github.com/paramiko/paramiko/pull/438 locally and it does indeed fix my problem.

I guess I'll close this as a duplicate of 432.

**Comment by micahg** [comment]
So, maybe this is a dumb question, but is 438 ever going to get merged?

**Comment by deed02392** [comment]
You can access the banner through the transport still:

```python
        transport: paramiko.Transport = ssh.get_transport()
        remote_banner = transport.remote_version
```

**Comment by radssh** [comment]
Different banner - There is a plaintext exchange between client and server that indicates the ssh protocol version that each side can support (plus an identification string). This is what is preserved at the Transport level,  and available via `remote_version`.

There is also a banner that is (optionally) sent by the server during user authentication, specified in [RFC-4252](https://tools.ietf.org/html/rfc4252#section-5.4). Based on the way that Paramiko manages different user authentication methods, this get captured by the initial authentication method's `AuthHandler`, but then subsequently discarded if a new `AuthHandler` is created to take its place. The patch submitted elevates the population of the banner content into the `Transport` class instead of the `AuthHandler` class so it can persist across potential reconstruction of the `AuthHandler` objects.
