### ISSUE TITLE
Get error when install paramiko through "pip" command.

### ISSUE THREAD

**Issue by nhanlee97** [paramiko/paramiko#1562]
Hello everyone, 
I got the problem in the below pciture when I try to install paramiko by using the "pip" command. How to fix this problem. And, I installed the Cryptography package (python-crytography) before I did the "pip" command. 
Thanks in advance !
Nhan Lee

![python-error](https://user-images.githubusercontent.com/33399652/69793611-62c89f00-11fb-11ea-81f1-4a07417cda62.png)

**Comment by GPHemsley** [comment]
What version of Python and pip are you using?

**Comment by ploxiln** [comment]
Use the `-v` flag, e.g. `pip install -v paramiko`, to see more details. I suspect the problem is with the `PyNaCl` dependency

**Comment by nhanlee97** [comment]
Thanks everyone! I switch to another application. Thanks for all the supports. Have a nice day!

**Comment by vivekram87** [comment]
I got the exact same error with pycharm community edition.
The issue is with the version of pip or paramiko.
Use the latest version of pip (20) not 19 and paramiko ver 2.7 and not 2.7.1

use python -m pip install –upgrade pip

![2](https://user-images.githubusercontent.com/61583051/79686763-60c1b400-8260-11ea-916e-e0c6e69e1af8.JPG)

If ur using IDE
![1](https://user-images.githubusercontent.com/61583051/79686767-67502b80-8260-11ea-9796-afdac42905eb.JPG)
