### ISSUE TITLE
Unexpected exception from paramiko.RSAKey.from_private_key

### ISSUE THREAD

**Issue by jamercee** [paramiko/paramiko#1570]
According to the docs https://docs.paramiko.org/en/2.7/api/keys.html#paramiko.pkey.PKey.from_private_key_file, reading an invalid keyfile should raise an SSHException, but instead it seems to raise an AttributeError.

Tested on python3.8, Windows 10-Pro 64-bit, paramiko version 2.7.0

Example:
```
import paramiko
open('badkey', 'x').close()
paramiko.RSAKey.from_private_key('badkey')

```

```
Traceback (most recent call last):
  File "p.py", line 3, in <module>
    paramiko.RSAKey.from_private_key('badkey')
  File "C:\Program Files\Python38\lib\site-packages\paramiko\pkey.py", line 244, in from_private_key
    key = cls(file_obj=file_obj, password=password)
  File "C:\Program Files\Python38\lib\site-packages\paramiko\rsakey.py", line 52, in __init__
    self._from_private_key(file_obj, password)
  File "C:\Program Files\Python38\lib\site-packages\paramiko\rsakey.py", line 179, in _from_private_key
    data = self._read_private_key("RSA", file_obj, password)
  File "C:\Program Files\Python38\lib\site-packages\paramiko\pkey.py", line 300, in _read_private_key
    lines = f.readlines()
AttributeError: 'str' object has no attribute 'readlines'

```

**Comment by bitprophet** [comment]
If your example is accurate, the problem here is that you're giving Paramiko the literal string `"badkey"` instead of the result of the `open()` call, which is a Python file object. You might have better luck with:

``` python
import paramiko
keyfile = open('badkey')
key = paramiko.RSAKey.from_private_key(keyfile)
```

The error you get is because a string does not have the same API as a file-like object, so it's not really the same as getting an actual key file blob loaded up and finding it is incorrectly formatted.

**Comment by ChrisColbeckAtDuo** [comment]
@bitprophet code snippet worked but generates:
