### ISSUE TITLE
Classic SSH client works, paramiko can't open/connect socket

### ISSUE THREAD

**Issue by bopnrgi** [paramiko/paramiko#1654]
Hi, i'm facing a problem that I can't understand.

On my computer, I can do `ssh -p 22 User_A@IP_A` and successful login with public/private keys.
But it doesn't works with paramiko (up to date). The socket won't open, endless.

I've done a very simple script to try to debug it : 

```
import paramiko, logging
logging.basicConfig()
logging.getLogger("paramiko").setLevel(logging.DEBUG)

ssh_client = paramiko.SSHClient()
ssh_client.load_system_host_keys()
ssh_client.connect(hostname="IP_A",port=22,username="User_A")
```

1. i don't have any log, because Transport isn't started
2. there is nothing on prompt, no errors, except a very long time after 
2. I added a timeout, 10 seconds `ssh_client.connect(hostname="IP_A",port=22,username="User_A",timeout=10)`. the timeout is trigger correctly.

After debugging, it seams that script is blocked here `paramiko/client.py` at line
```
                try:
                    sock = socket.socket(af, socket.SOCK_STREAM)
```

On the remote server IP_A (AWS hosting), i monitored the SSH by` tail -f /var/log/auth.log` but i saw nothing incomming.

For your information, **the same script is working on another server** IP_B (OVH hosting), with appropriate credentials, of course.

Firewall problem, a SSH server configuration, or hosting settings ? don't know about this

Thanks for your reply

**Comment by acarlstein** [comment]
I'm had the same issue. For some unknown reason `paramiko` fails to do a default connection in the same way that the `ssh` command does. I tried different `paramiko` configurations, indicating the certificates, location of certificates, and such, but `paramiko` fails epically to connect. Which is a shame because I like the design of their API. It just that it isn't design to work by default as the `ssh` command does. I will try to install and use `sshpass` at this point because none of the tutorials or solutions in this repo's issue seems to be working.
