### ISSUE TITLE
struct.error: 'I' format requires 0 <= number <= 4294967295

### ISSUE THREAD

**Issue by weigu1** [paramiko/paramiko#1681]
Hi,

I get this error when using paramico (Kubuntu 18.04, 20.04). 

File "./pyshpcreator.py", line 482, in sync_files_sftp
    sftp.sync(src, dst, download=False, delete=True)
  File "/savit/programming/python/pyshpcreator/sftpsync.py", line 264, in sync
    self._save(file, dst_file, stat, remote=not download)
  File "/savit/programming/python/pyshpcreator/sftpsync.py", line 182, in _save
    self.sftp.utime(dst, (int(src_stat.st_atime), int(src_stat.st_mtime)))
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 580, in utime
    self._request(CMD_SETSTAT, path, attr)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 812, in _request
    num = self._async_request(type(None), t, *arg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 827, in _async_request
    item._pack(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_attr.py", line 137, in _pack
    msg.add_int(long(self.st_atime))
  File "/usr/lib/python3/dist-packages/paramiko/message.py", line 232, in add_int
    self.packet.write(struct.pack(">I", n))
struct.error: 'I' format requires 0 <= number <= 4294967295

A workaround is replacing all msg.add_int with msg.add_int64 in the method def _pack(self, msg): in sftpsync.py

Perhaps this could be changed in the source code

**Comment by ploxiln** [comment]
I don't think that the remote server will understand, if you switch from writing 4-byte integers to 8-byte integers. There does not seem to be a size indicator prefix here. If it seems to work for you, then the server is interpreting the first 8-byte int as two 4-byte ints and ignoring the second 8-byte int.

Also, your atime/mtime should not be over 4 billion. The current unix timestamp (seconds since 1970-01-01) is around 1589658036, while 4294967295 is in the year 2106, so it seems you are trying to send atime/mtime over 80 years in the future. More likely, you are accidentally sending milliseconds since 1970, or some other unrelated value, due to some bug.

**Comment by weigu1** [comment]
Thanks ploxiln for the explanations. I use sftpsync, and the problem comes perhaps from this older version with paramiko. I will change to another lib.

**Comment by weigu1** [comment]
I tried with a new version of sftpclone (instead sftpsync) and I get the same error while syncing my homepage. And again the workaround helps. I'm only using this lines in my python program :
sftpclone.SFTPClone(
        src,        
        "{}:{}@mysite.example.com:./mysite".format(login, password),
        port=sport
    ).run()

**Comment by weigu1** [comment]
Ok I found the culprit.
A corrupt file in my directory with a modified daze in 2106.
Thanks again for pointing in the right direction :)
