### ISSUE TITLE
SSH authentication failed - paramiko

### ISSUE THREAD

**Issue by ghost** [paramiko/paramiko#1703]
I'm currently running `Ubuntu 20.04` and using `Dask-SSH` to try to link up a SSH cluster for distributed machine learning with my other machines. 
I've installed openssh-server in Ubuntu which gives me an error when trying to set up the Dask-SSH cluster in the command line. 
I would type in the following `dask-ssh localhostip remotemachineip --ssh-usernname <username> --remote-python <path to python>`
However, when I send that command, I would get the following ```
```
paramiko.ssh_exception.AuthenticationException: Authetication failed.
 Retrying... (attempt 2/3)
[ dask-ssh ] : SSH connection error when connecting to 192.168.1.191:22to run '/opt/anaconda3/bin/python -m distributed.cli.dask_worker 192.168.1.108:8786 --nthreads 0 --host 192.168.1.191 --memory-limit auto'
SSH reported this exception: Authentication failed.
```
`Dask` is dependent on the `Paramiko` package. 
I've looked at different forums regarding this issue and even changed my SSH keys to the `-PEM `format (even though it should take `openssh` format by now)
Please help me with this issue. Note that I was able to SSH login to all my machines as I've copied the keys. 
Thanks,

**Comment by ChristopherRabotin** [comment]
Could your key be an RSAv2? if so, it seems like it isn't supported yet, cf. https://github.com/paramiko/paramiko/issues/1734 .

To know whether your key is RSAv2 instead of RSAv1, you've got [two options](https://superuser.com/questions/1444319/how-to-check-ssh-key-version-locally):
1. Check the public key file: if it only contains digits, then it's RSAv1. Else, it's RSAv2.
2. If the private key starts with "BEGIN OPENSSH PRIVATE KEY", then it's RSAv2.

**Comment by Dreamsorcerer** [comment]
As mentioned in the other thread, I don't think there's any such thing as a RSA2 key. If there's any options to display debugging information, then you might be able to get the caused from there (e.g. in openssh you can add the `-v` argument). Otherwise, you probably need to look at the ssh logs on the server to see what is happening.

I suspect that without either of these logs, it would just be blind guessing by anybody responding here. It could be related to that issue if the server is configured to disallow `ssh-rsa`.

**Comment by ChristopherRabotin** [comment]
My mistake, I meant to write SHA2 or SHA1, as implemented (maybe?) in https://github.com/paramiko/paramiko/pull/1643 .

**Comment by bitprophet** [comment]
Linked ticket is now closed & released!
