### ISSUE TITLE
no host keys found

### ISSUE THREAD

**Issue by hududed** [paramiko/paramiko#1771]
Hello

not sure if this is relevant. I use `pysftp` that looks for host keys at `~/.ssh/known_hosts` file at init.
The condition uses paramiko as such:
```
import paramiko

if len(paramiko.hostkeys.HostKeys().items()) == 0:
print('No Host Keys Found')
```

Basically this condition  `len(paramiko.hostkeys.HostKeys().items()) == 0` is true, although I do have an existing `known_hosts` file, which contains:

```
192.168.254.254 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCVlnFrb1SzjijeWRld0w+MJpblrsF8vEutsRnJbxOMHKz8dhqP/qGjYOtG3KCLwNH8odLStd5or5C68XqbdBTxXG1CaTrSd0Z4gWo3cNy3rKjJ4pmTVPuFXEH7iCfd9GNDfPtUOZDeJhbAXID8mUXtnGaw4jH3veWSmLGQk/sbNRgFfVytAqhGxn8wVgBmVt5VGmaQN9f35mikfmyRZtwQXwZ/sbvNYYiGVbd0mnztawAdv9CZhtdJBofj1yqldw/yfN7m/8AkKHqAOlRfbKMIXU+VXkKTwg+try/aYA76HJPmS5jU/C3esc/2wyZBP7t9fMOF6iUbimCsHCC2MP3P
```

Please advise on how to solve.

**Comment by ploxiln** [comment]
It could be that paramiko is failing to parse your `known_hosts` file, but more likely is that it is not being instructed to try to load that particular file. You can figure out what the case is and then drill in from there, by trying to manually load this host keys file:

```
>>> from paramiko import HostKeys
>>> hk = HostKeys("/Users/pierce/.ssh/known_hosts")
>>> len(hk.items())
16
```

If that works, then the issue is that pysftp is not telling paramiko to load your host keys file. (The `SSHClient` class has a `load_host_keys()` method...)

**Comment by hududed** [comment]
Hi

This issue was solved. The problem was my known_host file that I made via windows powershell ssh-keyscan created a UTF-16 encoded file. Converting to UTF-8 solved my problem.
