### ISSUE TITLE
Authentication Banner - get_banner not working as expected.

### ISSUE THREAD

**Issue by james-powis** [paramiko/paramiko#1834]
Originally discussed here: https://github.com/paramiko/paramiko/issues/273

`client._transport.get_banner()` is always None.

The goal here is to obtain the login banner / message which is presented to the user prior to the password prompt. Every attempt to work around this has failed with the exception of using pexpect.

```python
aecore@apollo00:~$ python3
Python 3.6.10 (default, Dec 19 2019, 23:04:32) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> 
>>> client = paramiko.SSHClient()
>>> client.load_system_host_keys()
>>> client.connect('1.1.1.1', username='myuser', password='mypass', look_for_keys=False, allow_agent=False)
>>> client._transport.get_banner()
>>> 
```
As documented we are getting None by default, however the cisco router we are connecting to absolutely has the following login banner.

```
$ ssh myuser@1.1.1.1


*******************************************************************************
*                                                                             *
*  This is a private computer system. It is for authorized use only. Users    *
*  (authorized or unauthorized) have no explicit or implicit expectation of   *
*  privacy.                                                                   *
*                                                                             *
*  Any or all uses of this system and all files on this system may be         *
*  intercepted, monitored, recorded, copied, audited, inspected, and          *
*  disclosed to authorized site, law enforcement personnel, as well as        *
*  authorized officials of other agencies.  By using this system, the user    *
*  consents to such interception, monitoring, recording, copying, auditing,   *
*  inspection, and disclosure at the discretion of authorized site personnel. *
*                                                                             *
*  Unauthorized or improper use of this system may result in administrative   *
*  disciplinary action and civil and criminal penalties. By continuing to     *
*  use this system you indicate your awareness of and consent to these terms  *
*  and conditions of use. LOG OFF IMMEDIATELY if you do not agree to the      *
*  conditions stated in this warning.                                         *
*                                                                             *
*******************************************************************************

Password:
```

The device in question is a cisco router.

**Comment by dorighetto** [comment]
Did you find a way to solve this problem? I'm looking for a resolution too.

**Comment by jun66j5** [comment]
That is not a paramiko issue. The `get_banner()` returns the [authentication banner](https://www.rfc-editor.org/rfc/rfc4252#section-5.4), not login banner.

It is needed to call `invoke_shell()` and receive messages from the shell in order to read the login banner.

**Comment by dorighetto** [comment]
I tried something with this, but no success. Would've a sample? Even in the
internet i didn't find anything like what I need.

Att, Leonardo.

Em qui., 13 de abr. de 2023 16:50, Jun Omae (大前 潤) ***@***.***>
escreveu:

**Comment by jun66j5** [comment]
Please share your tried and tested scripts. Why do you want to get a login banner? What do you actually want to do?

**Comment by dorighetto** [comment]
I will try to explain better... When I try a SSH connection by terminal a
just do something like this:
ssh ***@***.***
After this a receive a banner asking for an authentication:

[image: image.png]

At this moment I need to pass my network username and password. This is a
pre authentication in order to input the server password in the next step.
However when I try to do the same stuff with paramiko I just got an
error message during the paramiko.SSHclient.connect method:
paramiko.ssh_exception.AuthenticationException: Authentication failed.

And the following is the log of paramiko:

DEB [20230417-18:03:18.472] thr=1   paramiko.transport: kex engine
KexGroup14 specified hash_algo <built-in function openssl_sha1>
DEB [20230417-18:03:18.486] thr=1   paramiko.transport: Switch to new keys
...
DEB [20230417-18:03:18.507] thr=1   paramiko.transport: userauth is OK
INF [20230417-18:03:18.521] thr=1   paramiko.transport: Auth banner: b'
                                                               \r\n ____  _
  _ _____ _     _       ____    _    _        _    ____ ___ _____ \r\n/
___|| | | | ____| |   | |     | __ )  / \\  | |      / \\  | __ |_ _|_
_|\r\n\\___ \\| |_| |  _| | |   | |     |  _ \\ / _ \\ | |     / _ \\ |  _
\\| |  | |  \r\n ___) |  _  | |___| |___| |___  | |_) / ___ \\| |___ / ___
\\| |_) | |  | |  \r\n|____/|_| |_|_____|_____|_____| |____/_/
\\_|_____/_/   \\_|____|___| |_|  \r\n

\r\n============================================================================\r\n
         A PARTIR DESSE MOMENTO A SUA SESSAO ESTA SENDO GRAVADA  \r\n
          DE ACORDO COM OS PROCEDIMENTOS DA
TIM.\r\n============================================================================\r\n
    \r\n'
DEB [20230417-18:03:18.917] thr=1   paramiko.transport: EOF in transport
thread

That's my code:

pa.util.log_to_file('log_paramiko', level='DEBUG')
ssh = pa.SSHClient()
ssh.set_missing_host_key_policy(pa.AutoAddPolicy())
ssh.load_system_host_keys()
ssh.connect(hostname='server', username='user', password='any stuff',
banner_timeout=30)



I tried a lot to find a way out in many forums but no success. Since now I
thank you a lot for all your attention.

Att, Leonardo.

**Comment by jun66j5** [comment]
Sorry for my late reply.

> DEB [20230417-18:03:18.507] thr=1 paramiko.transport: userauth is OK
> INF [20230417-18:03:18.521] thr=1 paramiko.transport: Auth banner: b'...'
> DEB [20230417-18:03:18.917] thr=1 paramiko.transport: EOF in transport thread

Typically, the following should be logged between `userauth is OK` and `EOF in transport thread`, but not logged.
```
paramiko.transport: Authentication (password) failed.
```

Could you please try the following script and post `/tmp/paramiko.log` and the output of the script?

```python
import paramiko
paramiko.util.log_to_file('/tmp/paramiko.log')
hostname = 'server'  # replace with hostname of your server
port = 22            # replace with port number of your server
t = paramiko.Transport((hostname, port))
t.start_client()
print(t.auth_none('user'))  # should raise AuthenticationException
```

**Comment by bskinn** [comment]
It's now been three months since the last action on this ticket. I'm going to go ahead and close.

If help is still needed here, please feel free to reopen and continue the conversation.
