### ISSUE TITLE
Paramiko not working with Openssh 8.8p1

### ISSUE THREAD

**Issue by flavius** [paramiko/paramiko#1915]
After an upgrade of openssh from 8.7p1 to 8.8p1, paramiko does not work any more.

Sample script:

```
  def native_ssh_command(self, host, username, cmds, debug=True):
    results = []

    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.WarningPolicy())
    client.connect(host, 22, username)
    session = client.get_transport().open_session()
    paramiko.agent.AgentRequestHandler(session)
    for cmd in cmds:
        if debug:
            print(cmd)
        (stdin, stdout, stderr) = client.exec_command(cmd)
        cmd_result = {"cmd": cmd, "stdout": stdout.read(), "stderr": stderr.read(), "exit_code": stdout.channel.recv_exit_status()}
        results.append(cmd_result)
        if stdout.channel.recv_exit_status() != 0:
            if debug:
                print(f"Command '{cmd=}' failed on host '{host=}'!")
                print(cmd_result)
            break;
    client.close()
    return results
```

**Comment by austinbutler** [comment]
As stated using an ED25519 key works. I was able to get an RSA key working by combining https://github.com/paramiko/paramiko/pull/1643 and https://github.com/paramiko/paramiko/pull/1606 in a branch off `paramiko` 2.8.0.

**Comment by manfred-kaiser** [comment]
The problem is, that "ssh-rsa" has multiple meanings. One problem with paramiko is, that it reads the key-type from a publickey file and this type is used as hash type during the authentication. This only works for sha1 hashes, because they are also defined as "ssh-rsa".

According to RFC-4252, publickey authentication is split in 2 steps. The first (optional) step is to ask the server, if a publickey is known. In the second step a signature is sent to the server, which is the real authentication step.
If the first step fails, because SHA1 hashes are not supported, the whole authentication fails.

When speaking of hash types SSH defines **ssh-rsa** as SHA1 hash. For SHA512 hashes the hash type is **rsa-sha2-512**.

I have implemented a test application, which is able to lookup, if a publickey is known by the server. This application only implements the first step of the publickey authentication process. When using the current implementation of paramiko, the key lookup fails for OpenSSH 8.8.

If the key is a "ssh-rsa" key type, my application forces a "rsa-sha2-512" hash, and the key loopup is possible:

https://github.com/ssh-mitm/ssh-mitm/blob/dbc920d9a93304b24a5b71d766c6210c531eb9b8/ssh_proxy_server/authentication.py#L52:L55

In the mentioned pull requests, there is not change in the ``PublicBlob`` class. The ``PublicBlob`` class must use a supported hash algorithm.

We will try to fix this issue in the next weeks. Is there a deadline for the fix?

**Comment by bitprophet** [comment]
Paramiko 2.9 will be out today and fixes this!
