### ISSUE TITLE
Close the connection and connect again, login error "Authentication failed."

### ISSUE THREAD

**Issue by dancer430** [paramiko/paramiko#1946]
When I close the connection and  connect again(maybe more than twice in a few seconds), program runs error and tells me "Authentication failed." even the username and password are right
Can someone helps me?

**Comment by bskinn** [comment]
Given that the related issue was due to a server timeout, and given that relatively little detail was provided in the initial ticket, I am going to close on the assumption that this is not a paramiko issue, but instead something on the server side.

@dancer430, if you're still facing this issue, please create a [new support ticket] with all of the info requested by the issue template. Thanks!

[new support ticket]: https://github.com/paramiko/paramiko/issues/new?assignees=&labels=Support&projects=&template=10_support_request.yml&title=%5BSUPPORT%5D+-+%3Ctitle%3E
