### ISSUE TITLE
open_sftp() can block up to an hour

### ISSUE THREAD

**Issue by ilija-lazoroski** [paramiko/paramiko#2009]
Hey all, I want to report a bug that @VakarisZ and me found.

It comes from `open_sftp` function on SSHClient which can block up to an hour, if a machine is killed after connecting

To reproduce it just connect to a VM machine, set breakpoint before calling `open_sftp`, pause the VM machine and run the `open_sftp`. It will wait up to an hour until it timeouts. I have waited 14 minutes and then unpaused the VM which unblocked the `open_sftp` function.

What I purpose for a solution is that we add timeout argument to `open_sftp`.

Here is a snippet code I used to reproduce the block:

```import paramiko
import datetime
import pdb

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.WarningPolicy)

ssh.connect("x.x.x.x", port=22, username=username, password=password, timeout=10,
            auth_timeout=10, banner_timeout=5)

print(datetime.datetime.now())

pdb.set_trace()

with ssh.open_sftp() as ftp:
    print(datetime.datetime.now())


print(datetime.datetime.now())
```

**Comment by mssalvatore** [comment]
The call chain looks like:

 `SSHClient.open_sftp()` -> `Transport.open_sftp_client()` -> `SFTPClient.from_transport()` -> `Transport.open_session()` -> `Transport.open_channel()`

The timeout in `Transport.open_channel()` is set here:
https://github.com/paramiko/paramiko/blob/57033fb57986a00263e57c615674bfec41efb59c/paramiko/transport.py#L1014

Since `SSHClient.open_sftp()` doesn't accept a timeout, `None` is passed down the stack and `timeout` is set to 3600

The below code contains the logic for the timeout:
https://github.com/paramiko/paramiko/blob/57033fb57986a00263e57c615674bfec41efb59c/paramiko/transport.py#L1044-L1054


One solution might be to add an optional `timeout` parameter to `SSHClient.open_sftp()`, `Transport.open_sftp_client()`, and `SFTPClient.from_transport()`
