### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [paramiko/paramiko#2027]
Could you please consider to utilize built-in unittest.mock instead of mock, as a fallback at least?

**Comment by bskinn** [comment]
Can you explain in more detail the problems you're encountering from the use of `mock` instead of `unittest.mock`?

**Comment by pghmcfc** [comment]
Downstream distributions are trying to get rid of `mock`, e.g.:

https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

Here is the patch I use for the Fedora build of `paramiko`:
https://src.fedoraproject.org/rpms/python-paramiko/blob/rawhide/f/0003-remove-mock-dep.patch

**Comment by pgajdos** [comment]
Sure, we can keep patches temporarily. Thanks for your attention!

**Comment by bskinn** [comment]
For reference, on what timeframe would you hope to be able to drop the patches?

An intermediate step with the guarded import & fallback to `unittest.mock` might be feasible sooner.

**Comment by pghmcfc** [comment]
I'll keep the patch in Fedora as long as it's needed to build without `mock`. I want to be able to build without `mock` because it hasn't been packaged for the upcoming Red Hat Enterprise Linux 9 and I prefer to be able to build the same package on all of my target distribution releases where possible. So there's no big rush for this from my perspective - it's not hard to maintain this patch downstream if I have to.

The previous link won't work any longer as I renumbered the patches when I did the update for 2.10.4, so it's now here:
https://src.fedoraproject.org/rpms/python-paramiko/blob/rawhide/f/0004-remove-mock-dep.patch

The patch already does the guarded import and fallback, except with `unittest.mock` as the preferred option and falling back to `mock` if necessary, I'd be happy to provide the patch as a pull request if that was helpful.

**Comment by bskinn** [comment]
Ok, probably will just aim it for 3.0, then.

Although, a further question: is Fedora packaging older release lines of paramiko? That is, e.g., 2.8 and 2.9 and 2.10? Or, just `latest`? If the former, cherry picking a guarded-import version back to those lines would be important.

A PR with guarded imports would be fantastic...should simplify all of the needed workflow getting this incorporated. Thanks!

**Comment by pghmcfc** [comment]
I only have 2.10.x in all current Fedora releases, but in EPEL (Fedora packages built for Red Hat Enterprise Linux and its clones) I still have 2.4.3 in EPEL-8 and Red Hat package `paramiko` 2.1.1 themselves for RHEL-7. These versions reflect the reluctance to do significant version updates for stability reasons in enterprise environments. I did backport the fix for CVE-2022-24302 to 2.4.3 for EPEL-8 though.

**Comment by pghmcfc** [comment]
No intention of fixing this back there anyway, they're stuck with old python versions too so it doesn't matter.

**Comment by bskinn** [comment]
Got it. Bumped this to @bitprophet's attention for him to prioritize/milestone.

**Comment by bitprophet** [comment]
Yea we're dropping Python 2 and <3.6 next release, so this will become moot. Thanks!
