### ISSUE TITLE
CVE-2022-24302 fix not part of 2.9.3 release

### ISSUE THREAD

**Issue by bdrung** [paramiko/paramiko#2029]
https://www.paramiko.org/changelog.html claims that the 2.9.3 release contains the fix for CVE-2022-24302, but neither the 2.9.3 tag nor the 2.9 branch contain the fixing commit 4c491e299c9b800358b16fa4886d8d94f45abe2e. Please include the fix in your next 2.9.x release.

**Comment by bskinn** [comment]
Thanks for reporting this -- I asked @bitprophet, and he said that the changes needed to fix this CVE were tightly intertwined enough with other changes that went into 2.10, and also represented enough of a change in behavior, that the fix was intentionally not backported to 2.9 and earlier. 

If you need this fix, you'll have to use 2.10+

**Comment by bdrung** [comment]
Then please remove the CVE fix entry for 2.9.3 from https://www.paramiko.org/changelog.html

**Comment by bitprophet** [comment]
Bug wasn't correctly flagged in the changelog as being 2.10-only - that's been fixed just now and the docs should reflect this in a few minutes. Thanks!
