### ISSUE TITLE
Why can't I execute the cd command?

### ISSUE THREAD

**Issue by zhenzi0322** [paramiko/paramiko#2042]
```python
import time
import paramiko

ssh = paramiko.SSHClient()
know_host = paramiko.AutoAddPolicy()
ssh.set_missing_host_key_policy(know_host)
ssh.connect(
    hostname="192.xxx.0.xx",
    port=22,
    username="root",
    password="xxx"
)

channel = ssh.get_transport().open_session()
channel.get_pty()
channel.invoke_shell()

while True:
    command = input("root@demo:")
    if command == 'exit':
        break
    channel.send(command)
    while True:
        if channel.recv_ready():
            output = channel.recv(1024)
            stdin, stdout, stderr = ssh.exec_command(output)
            print(stdout.read())
        else:
            time.sleep(0.5)
            if not (channel.recv_ready()):
                break
ssh.close()
```

**Comment by bskinn** [comment]
Please provide more detail about what you are trying to do, what you think should happen, and what's going wrong instead.

Can you provide an example terminal session where you try to use this code?

What Python and paramiko versions are you using?

**Comment by zhenzi0322** [comment]
> Please provide more detail about what you are trying to do, what you think should happen, and what's going wrong instead.
> 
> Can you provide an example terminal session where you try to use this code?
> 
> What Python and paramiko versions are you using?


I'm trying to make a great interactive program.But the cd command has no effect.

**Comment by bskinn** [comment]
> I'm trying to make a great interactive program.But the cd command has no effect.

Yes, I understand that `cd` isn't working the way you expect. 

In order to help fix the problem, you need to provide examples of commands you've attempted to run using `cd`, and the output/results you've gotten from running those commands.

**Comment by zhenzi0322** [comment]
> Please provide more detail about what you are trying to do, what you think should happen, and what's going wrong instead.
> 
> Can you provide an example terminal session where you try to use this code?
> 
> What Python and paramiko versions are you using?


python version: 3.7.5
paramiko version:  2.11.0

**Comment by tking-silver-peak** [comment]
This appears to be a bug in Paramiko. I was able to cd to directories, however was not able to cd to a symbolic link. This appears to be what @zhenzi0322 hit.
Python: 3.11.4
Paramiko: 3.3

**Comment by bskinn** [comment]
Thanks very much for this diagnosis, @tking-silver-peak!

Switching this to a feature request for now, given that it likely will require specific implementation of tooling to handle this.

**Comment by bskinn** [comment]
@tking-silver-peak Hm, I think what you've encountered is a separate issue. Unless I'm badly mistaken, `/mnt` is not a symlink, it's a standard directory. If you would like to be able to cd to symlinks, please create a new feature request ticket for that.

@zhenzi0322, based on other issues I've seen, I believe the problem you're running into is that `exec_command()` doesn't reuse the same shell across multiple invocations--per [the docs], it creates a new `Channel` every time, which resets the `pwd` to the default login directory. (@jun66j5, can you double-check me on this? Thanks!)

If you're trying to use Python to run commands across an SSH connection, I recommend trying the higher-level [Fabric] project first, rather than using the low-level paramiko.

I'm going to close this for now. Please feel free to continue discussing in the closed thread, though.

[the docs]: https://docs.paramiko.org/en/2.4/api/client.html#paramiko.client.SSHClient.exec_command
[fabric]: https://www.fabfile.org/

**Comment by jun66j5** [comment]
> @zhenzi0322, based on other issues I've seen, I believe the problem you're running into is that `exec_command()` doesn't reuse the same shell across multiple invocations--per [the docs](https://docs.paramiko.org/en/2.4/api/client.html#paramiko.client.SSHClient.exec_command), it creates a new `Channel` every time, which resets the `pwd` to the default login directory.

When the server accepts an `exec` request, it executes the command as a new process, like "$SHELL -c <command>". Even if you change the directory using the command, it will not be used for other `exec` requests. Also, this is a behavior of the OpenSSH server and is not a issue in paramiko.
