### ISSUE TITLE
Why is the ciphers list in the order that it's in?

### ISSUE THREAD

**Issue by fiendish** [paramiko/paramiko#2044]
Can someone explain why Paramiko prefers 128 bit first then 192 then 256 bit ciphers in https://github.com/paramiko/paramiko/blob/617b5cbe19145e076d2ee02d588a371a80559931/paramiko/transport.py#L149-L163
?

Why not prefer the stronger?

**Comment by bitprophet** [comment]
Almost certainly just because whoever added these put them in arbitrary order; or perhaps because they were added piecemeal over time and folks just kept appending. This entire part of Transport is likely to get shaken up soon anyways, it's all a mess and very fragile atm. Keep an eye out for that in the changelog.
