### ISSUE TITLE
doesn't fall back on ipv4 route when there is no ipv6 route

### ISSUE THREAD

**Issue by driesdesmet** [paramiko/paramiko#22]
I can't connect to a ssh server that has an AAAA record from a client that doesn't have an ipv6 route:

Python 2.6.1 (r261:67515, Jun 24 2010, 21:47:49) 
[GCC 4.2.1 (Apple Inc. build 5646)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> client=paramiko.SSHClient()
>>> client.connect(hostname='ssh.alwaysdata.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.6/site-packages/paramiko/client.py", line 296, in connect
    sock.connect(addr)
  File "<string>", line 1, in connect
socket.error: [Errno 65] No route to host

I would expect paramiko to use IPv4 in this case. Connecting with os x's default ssh client works as expected.

**Comment by tgoodlet** [comment]
Oh man. This still isn't fixed hehe?
ipv6 is like trying to push craft beer on people :D

**Comment by bitprophet** [comment]
Whoa now, I'm actually drinking a craft beer right now! ([Proof](https://untappd.com/user/bitprophet/checkin/152588453))

Interestingly I could swear I remembered merging a fix related to this, but maybe it's just my memory of the comments I left above. Gonna poke & see.

**Comment by bitprophet** [comment]
Confirmed that the current state of the code has the problem this is fixing (tries only 1st resolved address/family).

The latest state of https://github.com/Bluehorn/paramiko/compare/issue22 looks good. My only worry is if some platforms not under test raise socket exception types not included in `(ECONNREFUSED, EHOSTUNREACH)` (e.g. I remember other issues discovering fun subtle differences between Mac/BSD and Linux, where the same scenario yielded different exception numbers.) However that's not worth blocking a merge.

**Comment by bitprophet** [comment]
As I merge I notice that my earlier concern still isn't fully addressed, if we encounter errors which *are* conn-refused/host-unreachable, and they persist for *all* address families, they will be hidden and then we'll just die farther down the file when `socket` is unset/None.

Will attempt to recreate a few scenarios to confirm that this is an issue & to verify a fix.

**Comment by yaccz** [comment]
I think paramiko should also accept the connection hints (addrinfo) in a user controlled way so the user can for example say he wants just ipv4 addresses

**Comment by bitprophet** [comment]
I agree, @yaccz, though I'd prefer to take things one step at a time :)

**Comment by bitprophet** [comment]
Confirmed that the "wholly unreachable address == no bueno" scenario does raise a totally inscrutable error (an `EOFError` from attempts to `.start_client()` in `Transport`, at least when run via Fabric). Which also happened to trigger fabric/fabric#1263!

**Comment by bitprophet** [comment]
Confirmed I can recreate the real problem here by disabling IPv6 on my Mac's sshd config, reloading sshd, and then trying to use paramiko to talk to `localhost`. (For whatever reason, `getaddrinfo` on this platform is returning IPv6 first and IPv4 second - presumably the opposite scenario from @Bluehorn's setup (but same as @driesdesmet).

**Comment by tgoodlet** [comment]
@bitprophet Hah! 
Nice to see a fellow beer advocate at work. I've been meaning to sign up to untappd. Should really do that...

I was lucky enough to snag a case of [these] (http://www.ratebeer.com/beer/rodenbach-vintage/112249/) this week. 
Maybe I can start with that as my first rate.

Glad to see the issue get sorted out.
Thanks a ton!

**Comment by bitprophet** [comment]
I need to rename the exception I'm using here (Feels too general in hindsight), then make sure any pertinent docstrings & the changelog are updated, then merge.

**Comment by iElectric** [comment]
I've just hit an ipv6 bug, it's really annoying since it's hard to debug.

Make sure you have a public ipv6 address and run:

```
import paramiko as ssh

client = ssh.SSHClient()
client.connect(
    hostname='dogbert.kiberpipa.org',
    port=22,
)
```

Running python foo.py:

```Traceback (most recent call last):
  File "foo.py", line 6, in <module>
    port=22,
  File "/nix/store/dd1rf5bfds81wm588jagra109gbswas9-python2.7-paramiko-1.15.1/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/nix/store/dd1rf5bfds81wm588jagra109gbswas9-python2.7-paramiko-1.15.1/lib/python2.7/site-packages/paramiko/util.py", line 278, in retry_on_signal
    return function()
  File "/nix/store/dd1rf5bfds81wm588jagra109gbswas9-python2.7-paramiko-1.15.1/lib/python2.7/site-packages/paramiko/client.py", line 251, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/nix/store/nk1hw5c6jzin073difisgi0jfbbrqj7g-python-2.7.9/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied
```

**Comment by iElectric** [comment]
Main problem is that the ipv6 it returns is not accessible.

**Comment by bitprophet** [comment]
I think I ran into that while testing this, @iElectric - I'm gonna merge it soon because it at least fixes the original case, but see https://github.com/paramiko/paramiko/compare/try-multiple-address-families-22 which is the branch I've been working in.

**Comment by iElectric** [comment]
I don't have IPv6 address right now, but try connecting to `dogbert.kiberpipa.org`, it doesn't have ipv6 setup on the interface.

**Comment by bitprophet** [comment]
Tried it, both master and my branch work, but that's because my system is ending up with the IPv4 address first in the list returned by `socket.getaddrinfo` (this was a thing that complicated earlier troubleshooting as well).

The changes in the new branch should work for most permutations of the issue, and when I manually jigger it to e.g. reverse the results from `getaddrinfo`, things still work fine w/ your host. (If I do the same on master, I get `No route to host` - not `Permission denied` - but as far as I've seen there's lots of small differences between OSes and instances thereof which mean the specific error differs widely.)

**Comment by bitprophet** [comment]
Ran into a few minor issues with this after the fact:

* Forgot to rename the exception class as I'd been planning to, `ConnectionError` is too generic-sounding after all, my mistake.
* Code downstream in Fabric which catches `socket.error` assumes one can do `exception_obj[1]` to obtain the exception message string. This implies that most socket errors in the past were of the latter form as per Python core docs:

  > The accompanying value is either a string telling what went wrong or a pair (errno, string) representing an error returned by a system call

  Our subclass initializes using the superclass' `__init__` but only passes in the single message string. I should see whether it makes sense to initialize with an errno field (either a real error number that seems to map, or more likely, just None, because it is not a real OS level socket error.)
