### ISSUE TITLE
Forced to use disabled_algorithms={'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']} on OSx

### ISSUE THREAD

**Issue by arnodelorme** [paramiko/paramiko#2203]
```
ssh.connect(ssh_host, username=ssh_username, pkey=mykey)
```

fails but

```
ssh.connect(ssh_host, username=ssh_username, pkey=mykey, disabled_algorithms={'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']})
```

works

**Comment by bskinn** [comment]
Can you be more specific as to why this is a problem?

`disabled_algorithms` is currently the official workaround for multiple edge cases, until bitprophet finishes the key/auth overhaul of #387.

**Comment by arnodelorme** [comment]
This is a problem because transport.connect (paramika) and sshtunnel.open (sshtunnel) do not have the same workaround.

**Comment by bskinn** [comment]
Ok, thanks for that additional information. However, it still doesn't provide enough detail to understand your problem.

What are you trying to do, on what kind of platform? What is the code you're trying, and what error(s) are you getting?

**Comment by arnodelorme** [comment]
The following code will not work because "disabled_algorithms" is not an option for Transport. Similarly shtunnel.open (sshtunnel) will error because "disabled_algorithms" is not an option either. This is on OSX 12.3, Python 3.8 (also tried 3.11) and Paramika 3.1.0 (also tried 2.8 and 2.7.2). 

```
t = paramiko.Transport((host, int(port)))
t.connect(username=user, pkey=myrsakey, disabled_algorithms={'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']})
sftp = paramiko.SFTPClient.from_transport(t)
```

**Comment by bitprophet** [comment]
This sort of weird API mismatch between SSHClient and Transport may get better as we start solving #387, at least regarding the authentication related parameters like this one.

That said, your 2nd example is solvable by doing the "arguably correct" approach of creating an `SSHClient` with the algorithm params required, then calling that object's `open_sftp()` method to get your `SFTPClient`.

I don't maintain sshtunnel so I'm not sure what they do exactly, but see the top of my comment for the most likely solution, assuming that they themselves do have a legit need to create a `Transport` instead of an `SSHClient`.

**Comment by NiallN** [comment]
For those working with sshtunnel (last updated 2020) (@arnodelorme) as I am, I avoid the fallout if I install paramiko=2.7.2. 

If you install sshtunnel (pip install sshtunnel), it is pulling the latest paramiko (3.3.1 today during test). 
After installing sshtunnel, install paramiko=2.7.2 (pip install paramiko=-2.7.2 - this will uninstall the later version of paramiko too, e.g. 3.3.1).
