### ISSUE TITLE
[FEAT] - Improve support for custom authentication schemes

### ISSUE THREAD

**Issue by chrisinmtown** [paramiko/paramiko#2267]
I need to implement a kind of multi-factor authentication at a Cisco router. Basically the router shows a challenge on connection, and the client (that's me) has to compute a response and send it. Paramiko's `Transport` class provides support in the `auth_interactive` method, but using that seems to imply not using the convenient `SSHClient` class. I'm writing to ask if you would please consider ways to make this a little easier. Thanks for listening!

**Comment by chrisinmtown** [comment]
I see the `connect` method accepts a transport factory so I tried to figure out how to pass in a `Transport` object that's connected and authenticated. However the last action in connect is a call to `_auth` which is what I'm trying to avoid. Would it work if you extend `connect` to accept an argument that is an interactive authentication auth_interactive to pass to the `auth_interactive` method in the `Transport` object, and if that is present, don't all `_auth`? Just trying to throw out some possibilties, thanks for listening.

**Comment by chrisinmtown** [comment]
Closing.

**Comment by bskinn** [comment]
Wouldn't have been any bother. Apologies for the slow reply, I was at a conference when you posted this.

**Comment by chrisinmtown** [comment]
Greetings and thanks for the note, I'll reopen for discussion :)  

I found a solution of subclassing `SSHClient` and overriding the `_auth` method  here: https://github.com/ktbyers/netmiko/blob/develop/netmiko/paloalto/paloalto_panos.py  which works ok but is a little roundabout. I was trying to ask if you might consider making it easier to meet this need.

**Comment by bskinn** [comment]
@chrisinmtown, thanks for this -- bitprophet has been working on improving the flexibility of the key/auth tooling lately, per #387 and #23. I know there's more to implement, but there's a chance that what he's done already might let you do what you need.

Please check out the **experimental** new features described in the [3.2.0 paramiko CHANGELOG] (including the new `OpenSSHAuthStrategy` implementation in [Fabric 3.1.0]) -- it's possible that they may let you do what you need here on the user side, and not require changes to `paramiko` itself.

I'm not deeply familiar with what the current features enable, so I can't say for sure whether they address this use case. We would greatly appreciate any investigation you might be able to do and report back here, though. The new features will be fully added and finalized over the next few minor versions, so now is a great time to make sure your needs are factored into the functionality.

[3.2.0 paramiko changelog]: https://www.paramiko.org/changelog.html#3.2.0
[fabric 3.1.0]: https://www.fabfile.org/changelog.html#3.1.0

**Comment by chrisinmtown** [comment]
Thanks for the pointer to new features. The package already has what I require. I didn't have to make any changes to `paramiko` directly.  I could have simply used the `Transport` class. However I like the conveniences that `SSHClient` provides, so I chose the route of a subclass to achieve multi-factor authentication. And it was easy to copy/extend a working solution from Netmiko.

**Comment by bskinn** [comment]
Hm. I think we'll need more details of specifically what you're interested in seeing added in order to actually evaluate what you're asking for.

Also, it may be that what you're trying to do, depending on how low- vs high-level it is, might be better accomplished using Fabric (possibly with new functionality there) instead of paramiko. I don't know this for sure, but I'm wondering given your desire to use the higher-level `SSHClient` instead of `Transport`.

**Comment by chrisinmtown** [comment]
My ask here is rather small actually, probably could be addressed almost entirely with documentation!  I would like to post my code but don't want to reveal confidential information. I found at least two ways to implement the authentication, I'll sketch them. The less pretty version instantiates `Transport` directly, connects then calls its `auth_interactive` method with a custom handler that computes the response, creates a `Channel`, calls that class's `exec_command` method, finally calls `makefile` on the channel etc. to read the result. The slightly more pretty version subclasses `SSHClient` and overrides its `_auth` method. That new authentication method (actually tiny) checks the router prompts and if it finds the challenge, calls the `get_transport` method and then invokes `auth_interactive` with the same custom handler method mentioned above. My code instantiates an instance of the new subclass with the new parameters for responding to the challenge, then calls the client's very convenient `exec_command` to run a command and read standard output.

Does this help?

**Comment by bskinn** [comment]
> Does this help?

Yes, I think so - thanks for laying out how you were able to accomplish what you needed. (Suitably anonymized code would be even more helpful, but I understand that sometimes it's not possible to share.)

Since you were able to achieve this with paramiko as-is, I don't know if there's a strong prospect for a new feature around this (in code or in documentation), given that it sounds like a fairly idiosyncratic requirement for your situation and hardware.

If we get enough others coming by and expressing appreciation for your solution, then that would signal broad enough need to make a more compelling case for a new feature (or docs example, or demo).

But, for now, I'm going to go ahead and close the ticket.

Thanks again!
