### ISSUE TITLE
channel.recv_exit_status() hanging

### ISSUE THREAD

**Issue by kprantis** [paramiko/paramiko#448]
We are seeing channel.recv_exit_status() hanging seemingly indefinitely in certain cases. From some minor testing, it seems related to the size of the output returned. 

Consider the script below, when NUM_LOOPS=3500, the command executes just fine, and in only about ~1 second. But If I increase it to 4000, then it just hangs indefinitely. The number it hangs on appears to vary with the size of the output (aka, I can get to at least 10k if I echo 'banana' instead). Of course, this could all be a red herring, but thought I'd include it in case relevant.

```
import logging
import socket
import time
import paramiko
import re


def _ssh_address(address, command, timeout=30):
    """
    Executes a command on a remote server over ssh.

    Sends a command over ssh to a remote machine and returns the stdout,
    stderr, and exit status. It will verify that the exit status of the
    command matches expected_return_code unless expected_return_code=None.
    """
    print "remote_command[%s]: %s" % (address, command)
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    args = {'username': 'root'}
    print "SSH address = %s, args = %s" % (address, args)

    ssh.connect(address, **args)
    transport = ssh.get_transport()
    transport.set_keepalive(20)
    channel = transport.open_session()
    channel.settimeout(timeout)
    channel.exec_command(command)
    print "exec_command"
    exit_status = channel.recv_exit_status()  # Blocks until command succeeds
    print "recv_exit_status"
    stdout = channel.makefile('rb').read()  # Be sure to read before the channel closes
    print "stdout"
    stderr = channel.makefile_stderr('rb').read()
    print "stderr"
    channel.close()
    print "closed"
    return (exit_status, stdout, stderr)

if __name__ == '__main__':
    NUM_LOOPS=4000
    exit_status, stdout, stderr = _ssh_address('lotus-33vm15', 'for i in {1..%s}; do echo "Some random output from a command."; done' % NUM_LOOPS)
    print "Exit status %s" % exit_status
    print "stdout %s" % stdout
    print "stderr %s" % stderr
```

paramiko version is 1.7.5

**Comment by nchammas** [comment]
For the record, I ran into this same issue while running Paramiko 1.15.4. For a large enough output, `recv_exit_status()` hangs. The fix was the same: call `stdout.channel.recv_exit_status()` *after* calling `read()` on each of the output streams, instead of before.

I found this confusing for the same reason that @kprantis did. The [doc for `recv_exit_status()`](http://docs.paramiko.org/en/1.15/api/channel.html#paramiko.channel.Channel.recv_exit_status) makes it sound like it's safe to call first since it waits until everything is done.

> If the command hasn’t finished yet, this method will wait until it does, or until the channel is closed. If no exit status is provided by the server, -1 is returned.

@bitprophet - Does it make sense to add a warning somewhere in the documentation about how large output can cause hangs if `read()` and `recv_exit_status()` are not called in the correct order? Or is there perhaps a bug in the behavior of  `recv_exit_status()`?

I can work on a concise reproduction of the issue if it'll help you address this.

**Comment by bitprophet** [comment]
@nchammas I'd say it's even money on "intended and poorly documented behavior" versus "actual bug". Could be either. Given the codebase's age, though, I think even if it's technically a bug, it's evolved into "feature" by now. Especially since changing this kind of thing (it's likely threading/lock related) is risk-heavy.

So I'm leaning towards "add a `.. warning::` block to the docstring". If you've time, please by all means check the code itself in case there's something blindingly obvious (or if it makes documenting the corner case clearer) and otherwise, a warning would be better than just ignoring this.

Thanks!

**Comment by nchammas** [comment]
Here's a concise reproduction of the issue:

```python
import sys
import paramiko

print(sys.version)
print(paramiko.__version__)

client = paramiko.client.SSHClient()
client.load_system_host_keys()
client.set_missing_host_key_policy(paramiko.client.AutoAddPolicy())

client.connect(hostname='127.0.0.1')
output_len = 2097150

while True:
    stdin, stdout, stderr = client.exec_command(
        'printf %{}s'.format(output_len),
        get_pty=True)
    
    exit_status = stdout.channel.recv_exit_status()
    stdout_output = stdout.read().decode('utf8').rstrip('\n')
    
    print(len(stdout_output))
    output_len += 1
```

On my system, the output I get is:

```
$ python3 paramiko-large-output-hang.py 
3.5.0 (default, Sep 23 2015, 04:42:00) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
1.16.0
2097150
2097151
2097152
- hang -
```

So the largest output Paramiko can handle when `recv_exit_status()` is called first is 2097152 bytes, which is exactly 2 MiB. Any larger than that and it hangs. If I move `recv_exit_status()` to after the `read()`, Paramiko sails past that limit without issue.

Searching the codebase for 2097152, I found [this result](https://github.com/paramiko/paramiko/blob/2a99a8c9a4bde66720e9357963ce1896830528a1/paramiko/transport.py#L271-L273), though I wouldn't know if it explains this behavior.

I don't have time to dig further into this, but I can add the warning to `recv_exit_status()`'s documentation if that sounds good to you @bitprophet.

**Comment by bitprophet** [comment]
Transport window size could definitely have something to do with it, tho I'm rusty on the details (the joys of inheriting code you didn't write).

Doesn't really change the overall equation, though - until someone has time to seriously dig and determine whether the old documentation was 100% incorrect or if we've introduced a bug somewhere, the best time/efficacy tradeoff is just to amend said docs.

Since I'm looking at this (& am persnickety about language) I'll go write the warning myself now. thanks @nchammas !

**Comment by nchammas** [comment]
Sounds good to me. Thanks for maintaining Paramiko, @bitprophet.

**Comment by bitprophet** [comment]
Actually, I can confirm/deny the relationship to that window size variable by supplying a larger/smaller value to `myclient.get_transport().default_window_size` (as of 1.15 and up). Setting it much smaller makes the hang much sooner, setting it much larger, conversely likewise.

I still don't know enough about the details to know *why* this is happening but it makes me lean more towards "actual bug". But I've got other work I gotta do so still gonna slap the warning on here for now =/

**Comment by lamiastella** [comment]
Can you please have a look at this paramiko question?
http://stackoverflow.com/questions/34351455/paramiko-rtnetlink-answers-no-such-file-or-directory

**Comment by remram44** [comment]
These don't look like a paramiko problem at all. This page is about a specific issue and that issue has been addressed (though somewhat disappointingly). Please do not spam with unrelated demands.

**Comment by CharmingYang0** [comment]
It's hang sometimes when retrieving large output (nbyte=1024) even recv_exit_status() does not invoked.
I appreciate so much if someone hint how to solve it.

**Comment by remram44** [comment]
@CharmingYang0: what hangs? The call to `read()` itself?

**Comment by Madaditya** [comment]
Have you tried using
stdout_str = (channel.recv(len(channel.in_buffer)))
?
This might solve most issues.

**Comment by remram44** [comment]
Just recv() on the channel until exit_status_ready(). There is no reason to pass it the exact length like you do (and be mindful of races!)
