### ISSUE TITLE
Identity file (key) not found if there is a blank at the end of config file line

### ISSUE THREAD

**Issue by Aestu** [paramiko/paramiko#499]
Step to reproduce:

1.- Add a space at the end of IdentityFile line in ~/.ssh/config file
2.- Connect to this host using standard ssh: Everything is ok
2.- Try to connect to this host using paramiko: Error raises:

BackendException: ssh connection to root@xxxxxxx:22 failed: [Errno 2] No such file or directory: '/home/xxxxxx/.ssh/id_rsa '

**Comment by bitprophet** [comment]
Thought I saw a recent patch about trailing whitespace, can't find it but still looking.

Did find #375 which implies we *did* want this behavior but there's no actual rationale listed... 

EDIT: yea, there's a test that #375 was just making sure didn't get accidentally broken: https://github.com/paramiko/paramiko/blob/ade0c259ee1ad630a53998c77ce1d852e417aa50/tests/test_util.py#L113 - walking down the blame on that line leads me back to 02e81785104d97e0634e5a41e87f3b083ea0e952 ca 2006 by robey, which clearly means it's been "intended" behavior since the beginning of the codebase or near enough.

May dig farther in case there is rationale but usually code that old doesn't have a solid reason in the commit message. I honestly can't think of many reasons why trailing whitespace is something anybody wants, and as per #653's investigation, OpenSSH itself performs trailing whitespace stripping.

Pondering whether we should be super careful re: backwards compat, and fix this in the upcoming 2.0 release. But my gut says it's probably hurting many more people than it could possibly be helping, so maybe treating as a regular bug is the right approach.

**Comment by bitprophet** [comment]
Yea I can't find the patch I was remembering so I'm probably crazy or it was posted to another tracker. @56quarters if you want to draft a PR as follows, I'd merge it:

* Based on 1.13 branch, not master!
* Updates the existing test re: preserved trailing whitespace to prove that it *removes* trailing whitespace instead
* Makes sure the `\r\n` stuff still has tests & isn't broken (though I'm assuming `.strip()` would remove it as both chars are whitespace...). tho I dunno when that would even show up, might be a sign of codebase age heh.

**Comment by 56quarters** [comment]
Thanks @bitprophet, I'll probably come up with a PR this weekend.

**Comment by 56quarters** [comment]
PR that fixes this: https://github.com/paramiko/paramiko/pull/656

Thanks!

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Same patch produced the same failure twice.

Relevant files:
- paramiko/config.py: seeded from gold changed files (offline eval)
- tests/test_util.py: seeded from gold changed files (offline eval)

Attempts:
Attempt 1: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Attempt 2: success=False
File: paramiko/config.py
Result: {"command": "/home/morganbest/.repopilot/repos/paramiko-paramiko-work-venv/bin/python -m pytest tests/test_util.py", "returncode": 1, "success": false}
Error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/morganbest/.repopilot/repos/paramiko-paramiko-work-venv/lib/python3.11/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(_console_main())
                     ^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/paramiko-paramiko-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 253, in _console_main
    code = _main(prog=_get_prog_name(sys.argv))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/paramiko-paramiko-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 223, in _main
    config = _prepareconfig(new_args, plugins, prog=prog)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/paramiko-paramiko-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 410, in _prepareconfig
    config: Config = pluginmanager.hook.pytest_cmdline_parse(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/paramiko-paramiko-work-venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/para

Attempt 3: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Token usage: 16387/80000
