### ISSUE TITLE
Upgrading from V1.7.4

### ISSUE THREAD

**Issue by Ric-Techow** [paramiko/paramiko#506]
Have an application that uses paramiko V1.7.4.  Support is now required for ciphers aes128-ctr, aes192-ctr, aes256-ctr.

That is an old problems it seems.

But I would appreciate current advice on what would be the best action to take as there will have been a lot of change since 1.7.4.  

What would be the lowest advisable version to go for?  What risks might there be in installing the most current stable version?

Any application changes would be difficult.

**Comment by bitprophet** [comment]
If you don't need Python 3 or the features that landed after Python 3 support merged (which was [1.13.0](http://www.paramiko.org/changelog.html#1.13.0)), I'd probably start with the latest 1.10 or 1.12 release. 

Reason being that 1.10 added a lot of goodies vs 1.7-1.9, and 1.13+ are usable **but** there's been some instability due to the magnitude of the Python 3 merge - so 1.12 might be a little more stable (though it also doesn't get many patches anymore since the two branches are pretty divergent.)

Closing this since it's not actionable but you should still be able to comment after. Thanks!

**Comment by bitprophet** [comment]
Also, besides the aforementioned stability, there've been no intentional backwards incompatible changes (it's all still 1.x after all), so you *should* be able to get the latest release (1.15.x) and have it work. The earlier releases listed above are just the first good stepping stones.

**Comment by Ric-Techow** [comment]
Hi Bitprophet,  thank you very much for your advice and the detail you have given.  Appreciated.
