### ISSUE TITLE
How to implement server check_port_forward_request

### ISSUE THREAD

**Issue by shellster** [paramiko/paramiko#561]
Hi,

I'm trying to implement an SSH server in paramiko which allows port forwards.
I've implemented the check_port_forward_request method and returned the port I want the forward to be on.

My question:
Do I have to implement the local listener and somehow forward that back to the client/channel or does paramiko do that automatically?

If it does have to be implemented, is there an example?  I'm confused how I would implement such a beast since you don't know the requesting channel when check_port_forward_request is called.

Thanks in advance.

**Comment by bitprophet** [comment]
Hey, sorry, tickets aren't a great place for help discussions (though unfortunately, the mailing list is pretty barren too -- you might have some luck on IRC though depending on time of day.)

I'm closing this since it's not actionable but comments can continue to be left if you or someone else knows how to help. I don't know the answer off the top of my head, unfortunately.
