### ISSUE TITLE
[bug]   <paramiko.ChannelFile from <paramiko.Channel 3 (open) window=2097152 -> <paramiko.Transport at 0x3b58150 (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>

### ISSUE THREAD

**Issue by iloveyo123u1** [paramiko/paramiko#595]
my  code:

```
stdin, stdout, stderr = ssh.exec_command('git clone '+codeGit)
print(stderr)
for x in stdout.readlines():
    print("-"+x.strip('\n'))
```

---

print  stderr:

```
<paramiko.ChannelFile from <paramiko.Channel 3 (open) window=2097152 -> <paramiko.Transport at 0x3b58150 (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>
```

---

so i login to my server
and run:  

git clone git@123.123/1111.git

system tell me:

The program 'git' is currently not installed.  You can install it by typing:
apt-get install git

:)

thank you

**Comment by urban-1** [comment]
I think this can close since it is not a bug or an issue... 

I ended up with the same message with the following:

```
a,b,c = self.ssh.exec_command("rm %s" % tmp_file)
if c.read().strip() != "":
    lg.warning("Failed to clean remote patch file: %s" % c)
```

The warning reads:
```
<paramiko.ChannelFile from <paramiko.Channel 3 (EOF received) (open) window=2097152 -> <paramiko.Transport at 0xa38227b8 (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>
```

However, there are multiple things wrong with the above:

- `c` is actually the channel... not the content of `stderr`
- We already called `c.read()` there should be nothing else to read!
- Finally, in python3, if the stderr is empty it will read `b''` and should be compared to `b''` and not `''`

( ^--- maybe a sign to call it a week and go to the pub...)

For anyone in the same situation due to checking stderr for success/failure, if you can use exit code use it: `stdout.channel.recv_exit_status()`
