### ISSUE TITLE
Paramiko ignores exit-signal messages

### ISSUE THREAD

**Issue by nolar** [paramiko/paramiko#598]
Paramiko ignores the "exit-signal" messages. As per SSH specification, "exit-signal" messages are sent instead of "exit-status" when the command exits on signal (for example, on SIGKILL). See https://tools.ietf.org/html/rfc4254, points 6.9, 6.10.

Here is the command to simulate the behaviour (trap disables SIGTERM and causes timeout to use SIGKILL after 2 secs):

```
timeout --kill-after=1 1 $SHELL -c '
                trap "" SIGTERM
                exec sleep 5
'
```

The log fragment looks like:

```
2015-10-20 13:38:17,329 [Thread-91 ] [transport.py         ] [_log      ] [1440] [DEBUG]  Sending global request "keepalive@lag.net"
2015-10-20 13:38:22,275 [Thread-91 ] [channel.py           ] [_log      ] [1072] [DEBUG]  [chan 0] Unhandled channel request "exit-signal"
2015-10-20 13:38:22,276 [Thread-91 ] [channel.py           ] [_log      ] [1072] [DEBUG]  [chan 0] EOF received (0)

2015-10-20 13:38:22,278 [MainThread] [*****mylib.py*****] [ssh_proces] [752 ] [DEBUG]  ... Got exit code in ssh_process_output() for 10.x.y.z: -1
2015-10-20 13:38:22,278 [MainThread] [*****mylib.py*****] [exec_ssh  ] [874 ] [DEBUG]  Command Exit Code: (***) > Command: (timeout --kill-after=5 5 $SHELL -c '
                trap "" SIGTERM
                exec sleep 15
            ') Exit_Code: -1
```

Packages installed:
- remote side:
  *\* debian 7 wheezy
  *\* openssh-server 6.0p1
  *\* libssh2  1.4.2
- client side:
  *\* python 2.7
  *\* paramiko 1.15.3

The code for "exit-signal" handling is absent in https://github.com/paramiko/paramiko/blob/master/paramiko/channel.py#L946, next to "exit-status" handler.

The similar or the same issue is also mentioned in #434, but it is marked for non-standard platforms. Debian & OpenSSH is very standard.

**Comment by bitprophet** [comment]
Belatedly, thanks for the detailed description, greatly appreciated. I'm now wondering how Paramiko managed to *not* implement `exit-signal` for so long, I've maintained Paramiko-related stuff for years (and Paramiko for...now also years) and don't remember running across it.

**Comment by bitprophet** [comment]
Note to self, #434 has a very small patch in its description that should handle this or at least be a good starting point.

**Comment by bitprophet** [comment]
Torn between considering this a feature-add and a true bugfix. Will think on it. Either way it will definitely get released under the 1.x line.

**Comment by geromueller** [comment]
Please consider it a bug! We have a lot of unclosed connections due to this bug. (https://vispa.physik.rwth-aachen.de)

**Comment by bitprophet** [comment]
@geromueller Thanks for the info re: impact. To be clear, bug vs feature only changes whether it gets backported to eg 1.1.5/1.16/1.17, or if it is made available in a (likely otherwise very small) 1.18 release. Bug-vs-feature has no impact to me on *when* I merge & release, those would all go out at the same time.

In your case, are you strongly pinning your requirements to specific release lines (e.g. `paramiko>=1.16,<1.17`) or would any 1.x release suffice?

**Comment by geromueller** [comment]
For me/us "feature" would be okay.

**Comment by bitprophet** [comment]
Not entirely sure why the patch from #434 does things like `if repr(m.get_int())` and `int(0)`.

In fact, there are no `int`s at all in the RFC-described `exit-signal` message format:

>  The remote command may also terminate violently due to a signal.
   Such a condition can be indicated by the following message.  A zero
   'exit_status' usually means that the command terminated successfully.
>
>      byte      SSH_MSG_CHANNEL_REQUEST
>      uint32    recipient channel
>      string    "exit-signal"
>      boolean   FALSE
>      string    signal name (without the "SIG" prefix)
>      boolean   core dumped
>      string    error message in ISO-10646 UTF-8 encoding
>      string    language tag [RFC3066]

As far as I can tell, the patch calling `get_int` is always getting the integer length of the signal name field. Calling `get_int` also breaks parsing of the rest of the packet because now all the bytes are incorrectly offset! Hooray.

Anyway, I can successfully add my own clause that looks at both `get_string` values (in my testing - SIGHUP and/or SIGKILL to a running Python REPL - the second string, `error message`, is always blank. I wonder what situations or server implementations set it to interesting values?).

----

Which brings me to point number 2, what exactly are people hoping for here besides access to that signal string?

Dying due to a signal *is still an unexpected exit situation* by most standards, so Paramiko's default exit code value of `-1` is still nonzero and thus still correctly indicative of a program not exiting happily. I'm unable to get any actual exceptions or tracebacks out of this - just "oh yea I exited -1" when one calls `recv_exit_status()`. Changing it to exit 0 - which is what the other patch seems to half-accidentally do - seems wrong to me.

----

I actually went through this recently for local subprocesses in Invoke [here](https://github.com/pyinvoke/invoke/issues/406#issuecomment-259510495) and the upshot is that all one typically gets from a "real" subprocess is an "exit status" data structure that almost always has a number or two in it (that you tease out with things like `WEXITSTATUS`); signal-driven exits often result in negative numbers here.

Unfortunately, when it comes to SSH, all we have in this situation is what's in the `exit-signal` message, i.e. the signal name. No numbers.

Offhand all I can think of is "well, we could get a more useful non-zero number than -1, by mapping the names to some table". But that still doesn't quantitatively change the behavior here, which is again why I wonder what @geromueller and @nolar are looking for.

**Comment by bitprophet** [comment]
Amusingly, looking around for other handlings of `exit-signal` find the exact same apparently-incorrect attempts to read a number out of the message, instead of a string, e.g. http://stackoverflow.com/questions/3386233/how-to-get-exit-status-with-rubys-netssh-library

**Comment by geromueller** [comment]
Hi, i don't care about any exit code. The remote connection/channel should simply close on this event, and not serve/run forever a closed process.

**Comment by radssh** [comment]
See #823 (originally referencing #785) handles both sending **signal** to the server(which OpenSSH does nothing) as well as this case where the server sends the client **exit-signal**

**Comment by bitprophet** [comment]
@geromueller - in my testing my local client happily exits when the remote end is signal-killed, even without `exit-signal` handling present. Wondering what's different in your case. Hopefully moot once we merge something...

@radssh Argh, wish I'd remembered that those existed or that we'd linked either of them here, would have saved me more time :D gonna close this and move discussion to #823.
