### ISSUE TITLE
connect() having issues with exceptions

### ISSUE THREAD

**Issue by alchemyx** [paramiko/paramiko#643]
```
>>> import paramiko
>>> t = paramiko.Transport(('31.6.164.142', 22))
>>> try:
...   t.connect()
... except:
...   pass
...
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/paramiko/transport.py", line 1854, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/paramiko/packet.py", line 326, in readline
    buf += self._read_timeout(timeout)
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/paramiko/packet.py", line 482, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/paramiko/transport.py", line 1710, in run
    self._check_banner()
  File "/home/alchemyx/venv-ase/lib/python3.4/site-packages/paramiko/transport.py", line 1858, in _check_banner
    raise SSHException('Error reading SSH protocol banner' + str(e))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

So it seems that something is wrong or I misunderstood something? That host is quite odd:

```
$ ssh 31.6.164.142
ssh_exchange_identification: Connection closed by remote host
```

But still paramiko should handle it gracefully

**Comment by bitprophet** [comment]
What specifically were you expecting to happen in this case - have the `SSHException` about the banner be the actual exception raised? Something else? (Honest questions, not snark.)

I'm not sure what else "gracefully" could mean here :D the server presumably just clammed up during the banner part of connection setup, which I'd expect to cause a failure at some level...

**Comment by alchemyx** [comment]
My understanding was that if I catch all exceptions it should also catch this instead of spitting up error. 

-- 
Michał Margula, alchemyx@uznam.net.pl, http://alchemyx.uznam.net.pl/
"W życiu piękne są tylko chwile" [Ryszard Riedel]

Dnia 17.12.2015 o godz. 23:56 Jeff Forcier <notifications@github.com> napisał(a):

**Comment by bitprophet** [comment]
Aha, good point. I missed that particular detail, sorry.

This would be due to how threading and exceptions interact - exceptions that raise in a background thread never appear in the main thread, they just terminate their local thread & print a traceback.

And in this case, `Transport` is a thread class, and `Client.connect()` creates one and `start()`s it - thus the banner connect, etc all occur in a background thread.

So your main thread should not have actually excepted, though there's no great way (that I know offhand) to prevent the tracebacks from printing.
