### ISSUE TITLE
 'Error reading SSH protocol banner' got when try to connect in multi-thread

### ISSUE THREAD

**Issue by boyxiaolong** [paramiko/paramiko#664]
I try to use sshclient to conenct the same ssh server in multirhread.
when thread is below 10, it is ok.
when more than 20 threads are opened,  Error reading SSH protocol banner is got.

**Comment by radssh** [comment]
This is probably due to the server side dropping connections when handling accepting connections. There is typically a default limit of 10 connections that are permitted in an unauthenticated state. See sshd_config option **MaxStartups** description on your server host for default values and details.

You may be able to use a single Transport (or SSHClient) and handle individual Channels with independent threads, but be aware that there is another sshd_config parameter limit that you may encounter **MaxSessions** that limits the number of concurrent sessions (Channels) within a single Transport connection.

**Comment by crielly360** [comment]
We encountered this issue while simultaneously opening >10 connections. We increased MaxStartups value and added retry logic to handle it.
