### ISSUE TITLE
Paramiko 2.0.0 hangs when code is run on import or through a test runner (unittest, py.test, nosetests, tox)

### ISSUE THREAD

**Issue by seemethere** [paramiko/paramiko#735]
This issue relates to #104, and #721  which was fixed with @bucknerns `dirty hack` but the fix will no longer work when users upgrade to paramiko 2.0.0.

As outline in #104 the fix from @bucknerns is as follows:
```python
from paramiko import py3compat
# dirty hack to fix threading import lock (issue 104) by preloading module
py3compat.u("dirty hack")
```

However when upgrading to paramiko 2.0.0 the fix no longer works.

If you are using any sort of test runner (py.test, nosetest, tox, unittest) I would suggest downgrading to paramiko 1.17.0 using:
```shell
$ pip install paramiko==1.17.0 --upgrade 
```

Here is a gist of the diff between version 1.17.0 and version 2.0.0 of paramiko as of 4/30/2016: https://gist.github.com/seemethere/f161e829cd28cb57ed21c88e61165d71

If you would like to test this for yourself I would suggest the [sshaolin](https://github.com/bucknerns/sshaolin) module (it easily wraps paramiko to make it a bit easier to use the paramiko utilities):

**ssh_test.py**
```python
# logging to the terminal
import logging;root=logging.getLogger();root.addHandler(logging.StreamHandler());root.setLevel(0);
from sshaolin.client import SSHClient
client = SSHClient(hostname='your_hostname', username='your_username, password='your_password')
client.execute_command('ls -ltr')
```

And then trying to execute in an interpreter like so:

```shell
$ python
Python 2.7.11 (default, Jan  1 2016, 20:58:24)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ssh_test import *
```

**Comment by bitprophet** [comment]
@seemethere Were you experiencing the issue from #104 prior to upgrading to 2.0.0? And when you note in #721 that you downgraded to 1.17 and that "fixed" the issue - do you mean you're still applying the bizarro workaround from #104 too?

Trying to figure out exactly what's going on here re: which releases have which bugs, wondering if there are two different-but-similar race conditions or what. Suspect that if you *are* still using the #104 workaround, then it is the same issue, and I can roll this into #104 and consider it "still open, affecting both versions, not PyCrypto related apparently".

(Why 2.0 would make the workaround cease functioning is unclear to me, it doesn't seem PyCrypto related. But the original issue from the SO thread linked in #104 is also perplexing offhand; I don't see Paramiko auto-spawning threads on import anywhere by default.)

**Comment by bucknerns** [comment]
The workaround no longer functions because in 2.0 there is another import being made in the thread.  Basically to make a call that has a thread safe to run on import you have to preimport all modules that the thread is going to use.  In this case the thread is the transport class.  If any call it makes imports something implicitly it will deadlock because there is some sort of locking on the import call.(mutex or semaphore didn't dig in too much) 
https://docs.python.org/2/library/threading.html#importing-in-threaded-code

So to fix this completely, paramiko would need to find all the dependencies that are used starting from the run method in transport and preimport them before the call to start. (lots of work)

Or people running code at a global scope can just do a hack. #721 #104 #735
Keep in mind this hack is only tested with RSA keys and passwords, dsa, ec keys might need some other library preimported prior to thread call.

`
# dirty hack to fix threading import lock (issue 104) by preloading module
from paramiko import py3compat
py3compat.u("dirty hack")

# dirty hack 2.0 also issue 104
from cryptography.hazmat.backends import default_backend
default_backend()
`

**Comment by bitprophet** [comment]
OK, that sounds like "it's #104" so going to roll this into it. I really don't want a lot of open tickets for the same root issue :)
