### ISSUE TITLE
Channel.send incorrectly type hinted as str instead of bytes

### ISSUE THREAD

**Issue by johnthagen** [paramiko/paramiko#745]
[Channel.send](https://github.com/paramiko/paramiko/blob/master/paramiko/channel.py#L705) is marked in the docstring as taking a `str` type for parameter `s`.  In Python 3, this is incorrect because `str` is a unicode string, and `bytes` should be the correct type.  This would also make it more consistent with the prose of the docstring `Returns the number of bytes sent...`

Since Python 2.6 and 2.7 have the [`bytes` alias](https://docs.python.org/2/whatsnew/2.6.html#pep-3112-byte-literals) it would seem that `bytes` would be the appropriate type hint for all versions of Python `paramiko` supports.

`Channel.send` is just one example, but it looked like at least in the `channel` module there were others with this same problem.

The practical problem that the inconsistent docstring causes is that static analyzers like PyCharm parse the type hint from the docstring to help the developer.  In this case, it raises a false positive warning:

``` python
from paramiko.channel import Channel

c = Channel(0)
c.send(b'0000')  # PyCharm raises false positive here: "Expected 'str', got 'bytes' instead"
```

**Comment by wanlxp** [comment]
I have this question too, how to send bytes instead of str because i want to send chinese (which charset is gb2312)

**Comment by johnthagen** [comment]
@wanlxp Perhaps something like:

```py
from paramiko.channel import Channel

c = Channel(0)
c.send('國'.encode())
```

This would send at UTF-8.

**Comment by kootenpv** [comment]
I have now the opposite:

```
error: Argument 1 to "sendall" of "Channel" has
incompatible type "str"; expected "bytes"  [arg-type]
                channel.sendall(cmd)
```

cmd is a string and it sends just fine

**Comment by bskinn** [comment]
@kootenpv -- Indeed, this looks like something left over from Python 2 that needs to be converted to Python 3, now that Python 2 has been dropped in paramiko 3.0.

Are you interested in creating a PR to fix this?

**Comment by kootenpv** [comment]
Thanks for the response @bskinn! Not very familiar with typing tbh - the solution that worked for me was to simply encode the strings into bytes before sending - that worked well enough for me.

**Comment by bskinn** [comment]
Ok, no problem @kootenpv!

---

Although, taking a closer look -- I'm thinking that actually the typing in the paramiko codebase isn't meant to be strict.

The various `send` methods on `Channel` ultimately all call the private helper [`Channel._send`][channel _send], which [appends][add_string call] the passed content to a `Message` using [`add_string()`][add_string def].

`Message.add_string()` [coerces][util.asbytes call] to `bytes` using [`util.asbytes()`][util.asbytes def]—so, both Python 3 `str` and `bytes` are valid input types everywhere along this call chain.

So, yeah. The reason why the static typecheckers are complaining is because paramiko is not typed to formal specification. There is a request posted as #1780, for a `.pyi` stub file for paramiko, but it's not _only_ a matter of declaring types in a stub file; the correct types likely have to be _figured out_, and making the project type-consistent may actually be a pretty big project.

So, I'd (i) ignore the type-check errors and (ii) pay attention to #1780 -- that's likely where discussion will start.

Along those lines, I'm going to close this issue in favor of the broader #1780.


[add_string call]: https://github.com/paramiko/paramiko/blob/8d52c334b8b99eb96094edb1b513b26f864eeabd/paramiko/channel.py#L1201
[add_string def]: https://github.com/paramiko/paramiko/blob/8d52c334b8b99eb96094edb1b513b26f864eeabd/paramiko/message.py#L273
[channel _send]: https://github.com/paramiko/paramiko/blob/8d52c334b8b99eb96094edb1b513b26f864eeabd/paramiko/channel.py#L1189
[util.asbytes call]: https://github.com/paramiko/paramiko/blob/8d52c334b8b99eb96094edb1b513b26f864eeabd/paramiko/message.py#L279
[util.asbytes def]: https://github.com/paramiko/paramiko/blob/8d52c334b8b99eb96094edb1b513b26f864eeabd/paramiko/util.py#L308
