### ISSUE TITLE
NotImplementedError: Use module Crypto.Signature.pkcs1_15 instead

### ISSUE THREAD

**Issue by spaceone** [paramiko/paramiko#776]
Since some days I receive the following traceback:
```
$ python -c "import paramiko; ssh = paramiko.SSHClient(); ssh.connect('10.200.27.114', username='root', password='univention')"                                                                             
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 265, in connect
    t.start_client()
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 406, in start_client
    raise e
NotImplementedError: Use module Crypto.Signature.pkcs1_15 instead

```

How to fix it?

**Comment by bitprophet** [comment]
Please provide more details - see http://www.contribution-guide.org/#submitting-bugs for a guide on what level of detail is useful for bug reports. Thanks!

**Comment by jonasbardino** [comment]
This one sounds like an attempt to use paramiko with pycryptodome instead of pycrypto:
https://pypi.python.org/pypi/pycryptodome
http://www.xavierdupre.fr/app/pymyinstall/helpsphinx/blog/main_0001.html#post-2016-02-27-pycryptopycryptodomeparamikotoopenasshconnection-aggmain-0001
While the description of pycryptodome _sounds_ like it should be a drop-in replacement for pycrypto, I got the same error when trying out that setup, and the release notes explain that some features like Crypto.Signature.pkcs1_15  were removed:
http://pycryptodome.readthedocs.io/en/latest/src/changelog.html
so it is _not_ really a drop-in for pycrypto in relation to paramiko.

Searching the web for the particular NotImplementedError sounds like some projects or distributions silently made the switch from pycrypto to pycryptodome and broke stuff:
http://stackoverflow.com/questions/36501031/notimplementederror-use-module-crypto-signature-pkcs1-15-instead/36506902
http://agileadam.com/2016/04/paramiko-error-use-module-crypto-signature-pkcs1_15-instead/

I suppose this issue can be closed just pointing to the above reinstall pycrypto+paramiko workaround. 
Perhaps you'd still want to add pycryptodome support in paramiko as a wishlist / feature request, though.

**Comment by bitprophet** [comment]
Thanks @jonasbardino - yes, we've had issues in the past with people trying to use Cryptodome as a drop-in replacement. And yup, these days folks ought to be trying Paramiko 2.x for improved backend support / cryptography.io.
