### ISSUE TITLE
Encrypted Private Key not working when password is supplied with Gitolite server

### ISSUE THREAD

**Issue by drohm** [paramiko/paramiko#816]
I've read the following ticket in regards to fixes needed for handling keys: https://github.com/paramiko/paramiko/issues/387

but its not clear to me if the issues I'm having is a bug or if it's supposed to be fixed.

I'm trying to use a private key that's encrypted (uses a passphrase) and I'm passing in the password when loading the key, but I'm continually getting PasswordRequiredException:

``` python
pkey_filename = join(expanduser('~'), '.ssh', 'id_rsa')
pkey = paramiko.RSAKey.from_private_key_file(pkey_filename, password='password')
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('git', username='joes', pkey=pkey)
```

which outputs the following exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\paramiko\client.py", line 380, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\paramiko\client.py", line 603, in _auth
    raise saved_exception
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\paramiko\client.py", line 577, in _auth
    key = pkey_class.from_private_key_file(filename, password)
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\paramiko\pkey.py", line 196, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\paramiko\rsakey.py", line 45, in __init__
    self._from_private_key_file(filename, password)
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\paramiko\rsakey.py", line 163, in _from_private_key_file
    data = self._read_private_key_file('RSA', filename, password)
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\paramiko\pkey.py", line 268, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "C:\Python\.virtualenvs\releng-lib\lib\site-packages\paramiko\pkey.py", line 310, in _read_private_key
    raise PasswordRequiredException('Private key file is encrypted')
paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted
```

Am I doing something wrong or is this a known bug?

I've also read through this ticket: https://github.com/paramiko/paramiko/issues/768 and I've tried both approaches but end up getting the same exception.

**Comment by rajagennu** [comment]
Hello I went to documentation and found below lines

> classmethod from_private_key_file(filename, password=None)

`Create a key object by reading a private key file. If the private key is encrypted and password is not None, the given password will be used to decrypt the key (otherwise PasswordRequiredException is thrown). Through the magic of Python, this factory method will exist in all subclasses of PKey (such as RSAKey or DSSKey), but is useless on the abstract PKey class.`

**Comment by drohm** [comment]
@rajagennu Did you not see in my post that I did exactly that?

**Comment by radssh** [comment]
You are getting the `PasswordRequiredException` in the `client.connect()` call, not the `paramiko.RSAKey.from_private_key_file()` call. So your initial loading and decrypting of the private key looks like it is working fine. It looks like it doesn't do the job of successfully authenticating during `connect()`...

If the key that you are passing fails to authenticate, the connect will fall back to attempting keys available via SSHAgent, and then private keys in ~/.ssh, and finally username/password as a last resort. The (optional) password parameter to connect is used both as a private key passphrase if the key(s) found in ~/.ssh is encrypted, as well as the login password if connect() reaches the last option of password authentication. Since no password is being passed to connect, when it does find the id_rsa file in ~/.ssh, it can not load it without a passphrase, which causes the exception.

I suggest you add the parameter `look_for_keys=False` (and probably `allow_agent=False`) to the connect() call to explictly disable those attempts. That should fix the specific exception you are getting, but leave you with the puzzle of why the key isn't able to authenitcate.

**Comment by drohm** [comment]
@radssh I've tried passing the `password` parameter to the `connect()` function, but get the same exception.  I'll try using `look_for_keys=False` and `allow_agent=False` and see if that helps.

**Comment by drohm** [comment]
Turns out this is a Gitolite issue.  Gitolite handles the SSH logins and paramiko doesn't seem to work with it.  I can SSH to any other normal SSH server with no problems.

**Comment by poonia0arun** [comment]
I am running into a weird issue here. I am using paramiko to ssh into a remote host if I run program locally on a Centos host. It runs perfectly fine but when I use that program in cron jobs it fails after second attempt throwing private key file is encrypted. I am passing password in my program. Not sure what's going on here any input would be helpful.

**Comment by ploxiln** [comment]
As explained above, `PasswordRequiredException` often just means "auth didn't work", with no good clue as to why, it could be many different things.

This issue should be re-titled to something like "cannot authenticate with gitolite", or closed.

**Comment by AjackTi** [comment]
Me too! I was edit my code, but it is such error

**Comment by drohm** [comment]
Closing as this is more of an issue with how gitolite intercepts and handles the SSH sessions.
