### ISSUE TITLE
Paramiko Connect not Working

### ISSUE THREAD

**Issue by trend-setter** [paramiko/paramiko#817]
I was using Paramiko to connect to a VM through a VM from my system(2 jumps). While trying to connect to first VM im finding  error. IP is reachable through ping

`import paramiko
import sys
import subprocess

print "Connecting"
vm=paramiko.SSHClient()
vm.set_missing_host_key_policy(paramiko.AutoAddPolicy())
try:
	vm.connect('IP',22,username='####',password='****')
except paramiko.AuthenticationException:
    print "We had an authentication exception!"
except Exception as ist:
	print ist`

I'm getting this error 

> [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respondTraceback

Is it a proxy issue ? or something else. Please let me know

Thanks 
trend-setter

**Comment by bitprophet** [comment]
That's definitely a proxy or networking issue, it's the OS telling you the socket connection timed out or nobody was listening at the other end. Paramiko isn't what's raising the error itself.

I'd make sure you can connect to that IP and port via the OpenSSH client, or netcat (`nc -z IP 22`).

Closing as "can't fix" but please feel free to continue the thread, if I or others have the time we'll respond. Thanks!

**Comment by STejas91** [comment]
I am also facing same issue, i am trying to connect to one of VM for executing some commands, but getting same error as above "Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time [closed]"
the ping is working on the host VM.
`Pinging 10.30.15.243 with 32 bytes of data:
Reply from 10.30.15.243: bytes=32 time=331ms TTL=61
Reply from 10.30.15.243: bytes=32 time=546ms TTL=61
Reply from 10.30.15.243: bytes=32 time=247ms TTL=61

Ping statistics for 10.30.15.243:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 247ms, Maximum = 546ms, Average = 374ms`

below is my code please help !!

def establish_connection(host, hostname, username, domain):
    if '30' in host:
        print("its sc5")
        for key, value in password.rpass_dict.items():
            if key == 'SC5':
                for x in password.rpass_dict.get('SC5'):
                    print(x, hostname)
                    ssh_client.connect(hostname=hostname, username='root', password=x)
                    print("connection established")
                    if len(domain) == len('corp.coupons.com'):
                        adflush_reload(domain)

def adflush_reload(domain):
    if len(domain) == len('corp.coupons.com'):
        stdin, stdout, stderr = ssh_client.exec_command("adflush")
        print(stdout.readlines())
        stdin, stdout, stderr = ssh_client.exec_command("adleave")
        print(stdout.readlines())
        done = "done, check your login now"
    else:
        done = "not corp domain"
    return done
