### ISSUE TITLE
sftp listdir returns duplicate file names

### ISSUE THREAD

**Issue by cchwala** [paramiko/paramiko#826]
When using the `listdir` function of sftp I sometimes and randomly get duplicate file name entries in the returned list. When I use `listdir_iter` everything works as expected.
 
Example script:
```python
#!/usr/bin/env python

import paramiko
import collections

#print 'paramiko version = ', paramiko.__version__

user = 'my_user'
server = 'my_server'
remote_data_dir = 'my_data_dir'

# Connect to server
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy( paramiko.AutoAddPolicy() )
ssh.connect(server, username=user)
sftp = ssh.open_sftp()

# Get file list
print '\nGet file list via `listdir`'
fn_list = sftp.listdir(remote_data_dir)
print 'Length of `fn_list` = ', len(fn_list)

# Print duplicates
print 'Duplicates:'
print [item for item, count in collections.Counter(fn_list).items() if count > 1]

# Get iterater for files on server
print '\nGet files via `listdir_iter`'
fn_iter = sftp.listdir_iter(remote_data_dir)
fn_list = [fn for fn in fn_iter]
print 'Length of `fn_list` = ', len(fn_list)

# Print duplicates again
print 'Duplicates:'
print [item for item, count in collections.Counter(fn_list).items() if count > 1]

```

Output:
```
Get file list via `listdir`
Length of `fn_list` =  43338
Duplicates:
[u'TN_Ericsson_20161011_092809.dat.gz', u'TN_Ericsson_20161010_001800.dat.gz']

Get files via `listdir_iter`
Length of `fn_list` =  43338
Duplicates:
[]
```

Rerunning the script yields different duplicates or sometime none.

The number of files on the server grows constantly, with newly transferred files every minute. But the false duplicates are not within the newest files, so a possible update while `listdir` is working should not be the cause.

**Comment by bitprophet** [comment]
Interesting. The implementations of `listdir_attr` (which is what drives regular `listdir`) and `listdir_iter` do not seem very different, besides the way that `listdir_iter` uses an async methodology to generate its `CMD_READDIR` requests to the server.

The unpacking of the responses from the server is pretty straightforward: look at number-of-files int, iterate that many times, unpacking a filename & longname each time, then making an attribute obj from those and appending to list. If something was wrong here, such as iterating too many times, I would expect some sort of exception to occur.

Unless there's a subtle bug I'm not seeing at a glance, I'm wondering if this is somehow a hiccup on the server side in your particular case. Examining the response from the `READDIR` might make it clearer if the duplicates are in that network message, or if `listdir_attr` is itself somehow generating them after all.

**Comment by cchwala** [comment]
There are now less files (approx. 10.000) on the server, but I can still reproduce the bug after some retries.

Is there an easy way for me to check the `READDIR` response, as you suggested, or do I have to dive into the source code myself?

**Comment by cchwala** [comment]
After having taken a look at the code for `listdir` I see why you think it is most likely a hiccup of my server. The unpacking is really straightforward. Hence, the duplicate entry must already be contained in the response to the `CMD_READDIR` request.

When I find time, I will try with a different server.

**Comment by cchwala** [comment]
I could not reproduce the problem using a different client and different host.

However, I reran the above script with a small modification using the original client and server. I put a loop around the listdir-part to see if there is a pattern for the occurrence of the duplicates. Indeed, it seems as if the duplicates occur when new files are added to the directory on the server.

A further finding is that also `listdir_iter` returns duplicates in some cases.

Is it to be expected that `listdir` has problems when files are added while it is "working"?

**Comment by bitprophet** [comment]
That's good to hear that it may affect both methods similarly, as that makes way more sense.

I don't think I'd say the behavior you're seeing is "expected", other than the general issue of "iterating over state that is mutating during iteration, is often bug-prone".

Still smells like the core problem is server-side, but I'd want to confirm exactly what the RFC says about the defined behavior of `OPENDIR` and `READDIR` first.

OK...just skimmed the relevant bits of what I think is the right RFC, https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02 - it seems to say nothing about this sort of race condition / atomicity / etc. Which isn't terrifically surprising.

So it's going to come down to the server implementation & whether it attempts to provide any guarantees of an atomic snapshot of disk state at time the pseudo-filehandle is returned (in the `CMD_HANDLE` response to the client's initial `CMD_OPENDIR`). Otherwise it would presumably fall down into the behavior/usage of the filesystem APIs the server is using to communicate with its local OS.

What *is* your remote server in this case, is it OpenSSH or something else? Either way, I'd look in their docs/release notes/bug tracker for info about this behavior.

**Comment by cchwala** [comment]
When I do a `ssh -v remote_user@remote_server` I get:

```
OpenSSH_6.7p1 Debian-5, OpenSSL 1.0.1k 8 Jan 2015
```

**Comment by cchwala** [comment]
I tried finding a corresponding bug/fix/explanation in the OpenSSH documentation, but honestly I am quite lost, since I do not understand which exact command is executed on the server side, since I have problems decrypting the stuff that happens in `_async_request()` and `_send_packet()`.

I found some info on non-atomicity of sftp `put` and `get` methods, but not on how `ls` handles the case where files are added while it is working.

**Comment by bitprophet** [comment]
I am no C scientist, but the code for OpenSSH's side of things for readdir/opendir look pretty straightforward, as I expected they are simply wrapping the Linux IO calls (themselves named `opendir` and `readdir`, both in manpage section 3).

I was still suspicious that the nature of `readdir` meant it could in some situations return duplicate data, and googled, and found this: http://superuser.com/questions/640419/how-can-i-have-two-files-with-the-same-name-in-a-directory-when-mounted-with-nfs

Which seems to confirm that it can happen in some situations, on some filesystems, etc. I'd read that over carefully and see if the kernel version / FS type / etc you have on your server map to what those folks experienced.

Either way I'm 99.9% sure there's no bug in Paramiko that can be fixed\*, so I'm going to close this as non-actionable. Feel free to continue the discussion though :) Thanks!

\* We could potentially try to work around it, eg by storing the local results in a `set` or otherwise performing explicit deduplication, but I'd worry that this could introduce its own bugs down the line.

**Comment by cchwala** [comment]
Thanks!

I already have added a workaround in my code using a `set`. That is of course a really easy fix.

The only problem I see is that probably most people will not anticipate the unexpected behavior with the duplicate file names returned by `listdir`. However, as you wrote, the problem is on the server side and should, if possible, be fixed there.

The server I use is a VM and the storage is most probably NFS mounted or something similar, which could explain the behavior based on the thread you linked. I am in a chroot there, though. Hence, I have to wait for more info about the system from our IT department. If I can track down the implementation to blame, I will file bug report at the respective site.
