### ISSUE TITLE
Public Key Authentication

### ISSUE THREAD

**Issue by ThomasCoD** [paramiko/paramiko#888]
Hi I am having trouble getting Public Key Authentication to work with any other client then paramiko itself.
I have a Paramiko SFTP Server and Client they work together fine. But it does not work from Linux or Filezilla, or any other Client I tried so far. They all fall back on password authentication, which works fine.

The issue seems to be in the authentication request.
I always see this in the logs for any other client then paramiko:
Auth request (type=none) service=ssh-connection, username=me
instead of:
Auth request (type=publickey) service=ssh-connection, username=me

even though I force PK like this
ssh -o PreferredAuthentications=publickey -i /home/sshtest/.ssh/open_open me@testserver
This is done on debian testing: (Remote version/idstring: SSH-2.0-OpenSSH_7.4p1 Debian-6)
Paramiko: Local version/idstring: SSH-2.0-paramiko_2.1.1
Am I doing something wrong?

**Comment by radssh** [comment]
A typical ssh client is permitted to request authentication via a reserved method name of `none`. While not expected to result in a successful authentication, the server response of failure is expected to return a list of potentially allowed authentication methods. Not only does this allow the client to skip methods not offered by the server, it provides support for multi factor authentication.

Clients are not required to issue an initial auth request method of `none`, and may initiate request authentication methods of any type, which the server may or may not respond with a successful authentication response.

In your case, the paramiko sftp client requesting an authentication method of `publickey` will succeed, but a client that does an initial request of `none` gets a response that includes the default server implementation response from `get_allowed_auths()` of only `password`, so it bypasses attempting pubkey authentication ans skips straight to password.

Try overriding the `get_allowed_auths()` method to return 'publickey' instead of 'password' (or a comma separated list, if your implementation will support both). That should steer the other clients into trying publickey authentication to your server.

**Comment by ThomasCoD** [comment]
Thanks a million,
no it works from the command line. But I have another problem. Filezilla and my sftp library (Chilkat) always call check_auth_publickey twice even though the return value is AUTH_SUCCESSFUL.
Is this normal or a bug on the client?
Here is a log from Filezilla:
5124: 17-02-08 10:05:34.869: transport     (1567) : Auth request (type=none) service=ssh-connection, username=me
5124: 17-02-08 10:05:34.874: transport     (1567) : Auth rejected (none).
5124: 17-02-08 10:05:37.504: transport     (1567) : Auth request (type=publickey) service=ssh-connection, username=me
5124: 17-02-08 10:05:43.987: transport     (1567) : Auth request (type=publickey) service=ssh-connection, username=me
5124: 17-02-08 10:05:51.896: transport     (1567) : Auth granted (publickey).

**Comment by radssh** [comment]
That's probably a result of the client side doing public key authentication as a two step process. The protocol allows the client to pass just the public key (without the signature portion that proves the possession of the private key) as an inquiry to see **if** that key would be accepted. This can avoid unnecessary passphrase prompting for decryption of the private key, if the public key is screened ahead of time. 

If the server that the provided public key may be used to authenticate, then the client can send a second request that includes the verifiable signature component for the server to perform complete authentication. [RFC 4252](https://tools.ietf.org/html/rfc4252) does not require this pre-screening, so clients can attempt to authenticate with a single request that includes the signature portion.

**Comment by bitprophet** [comment]
Closing as "no action to take" but that doesn't prevent further comments :)
