### ISSUE TITLE
RC4 broken with cryptography 1.8.1

### ISSUE THREAD

**Issue by selb** [paramiko/paramiko#923]
With the latest `cryptography` release, connections to servers that negotiate RC4 fail at [transport.py:1679](https://github.com/paramiko/paramiko/blob/master/paramiko/transport.py#L1679) with `AttributeError: '_CipherContext' object has no attribute 'encrypt'`.

(This is not a request for continued RC4 support counter to #667; I only noticed this connecting to someone else's misconfigured server, which has since been fixed.)

**Comment by bitprophet** [comment]
Don't have time to look myself right now, but is this something to be considered a bug upstream, or was it an intentional API change on their part? That will determine whether the right action here is to report to upstream or for us to try papering over it. Guessing the latter would be hard since `.encrypt()` seems like an important API method...

**Comment by bitprophet** [comment]
Rolling this into just axing RC4 outright in the 2.0 lines, since it is a Bad Algorithm.
